export const waters = [
  "Ager",
  "Afritzer See",
  "Almsee",
  "Altausseer See",
  "Attersee",
  "Bregenzer Ach",
  "Brennsee",
  "Dobra-Stausee",
  "Donau",
  "Dornbirner Ach",
  "Drau",
  "Enns",
  "Erlaufsee",
  "Faaker See",
  "Flatschacher See",
  "Forstsee",
  "Fuschlsee",
  "Gail",
  "Glan",
  "Goggausee",
  "Gösselsdorfer See",
  "Grabensee",
  "Grundlsee",
  "Gurk",
  "Hallstätter See",
  "Hafnersee",
  "Hinterer Gosausee",
  "Hinterer Langbathsee",
  "Hintersee Faistenau",
  "Hörzendorfer See",
  "Ill",
  "Inn",
  "Irrsee",
  "Isel",
  "Kamp",
  "Keutschacher See",
  "Klopeiner See",
  "Kraiger See",
  "Lafnitz",
  "Lammer",
  "Lavant",
  "Lech",
  "Leiblach",
  "Leitha",
  "Leopoldsteiner See",
  "Liesingbach",
  "Lunzer See",
  "Längsee",
  "Magdalensee",
  "March",
  "Mattsee",
  "Millstätter See",
  "Mondsee",
  "Mur",
  "Mürz",
  "Neufelder See",
  "Neusiedler See",
  "Obertrumer See",
  "Ossiacher See",
  "Ottensteiner Stausee",
  "Ötztaler Ache",
  "Pielach",
  "Pinka",
  "Pleschinger See",
  "Pressegger See",
  "Raab",
  "Rauschelesee",
  "Saalach",
  "Salzach",
  "Silbersee",
  "Sonnegger See",
  "St. Andräer See",
  "St. Leonharder See",
  "Steyr",
  "Thaya",
  "Toplitzsee",
  "Traisen",
  "Traun",
  "Traunsee",
  "Turnersee",
  "Urbansee",
  "Vassacher See",
  "Vorderer Gosausee",
  "Vorderer Langbathsee",
  "Wallersee",
  "Weißensee",
  "Wienfluss",
  "Wienerwaldsee",
  "Wolfgangsee",
  "Wörthersee",
  "Ybbs",
  "Zeller See",
  "Zicksee",
  "Ziller"
];