// src/config.js

export const fishSpecies = [
  'Aal',
  'Aalrutte',
  'Adriastör',
  'Aitel',
  'Amur',
  'Atlantischer Stör',
  'Äsche',
  'Bachforelle',
  'Bachneunauge',
  'Bachsaibling',
  'Bachschmerle',
  'Barbe',
  'Bitterling',
  'Blaubandbärbling',
  'Brachse',
  'Donaukaulbarsch',
  'Dreistachliger Stichling',
  'Elritze',
  'Flussbarsch',
  'Frauennerfling',
  'Giebel',
  'Glattdick',
  'Goldsteinbeißer',
  'Gründling',
  'Güster',
  'Hasel',
  'Hausen',
  'Hecht',
  'Huchen',
  'Karausche',
  'Karpfen',
  'Kaulbarsch',
  'Kesslergründling',
  'Koppe',
  'Laube',
  'Malermuschel',
  'Moderlieschen',
  'Nackthalsgrundel',
  'Nase',
  'Nerfling',
  'Perlfisch',
  'Rapfen',
  'Regenbogenforelle',
  'Reinanke',
  'Rotauge',
  'Rotfeder',
  'Rußnase',
  'Schleie',
  'Schlammpeitzger',
  'Schneider',
  'Schrätzer',
  'Schwarzmundgrundel',
  'Seeforelle',
  'Seelaube',
  'Seesaibling',
  'Semling',
  'Sichling',
  'Sonnenbarsch',
  'Steingreßling',
  'Steinbeißer',
  'Sterlet',
  'Sternhausen',
  'Streber',
  'Tolstolob',
  'Ukrainisches Bachneunauge',
  'Waxdick',
  'Weißflossengründling',
  'Weißer Stör',
  'Wels',
  'Wolgazander',
  'Zander',
  'Zingel',
  'Zobel',
  'Zope',
  'Zwergwels'
];

export const waters = [
  'Achensee',
  'Ach',
  'Ager',
  'Aist',
  'Alfenz',
  'Alm',
  'Altausseer See',
  'Alter Rhein',
  'Antiesen',
  'Arbesbach',
  'Aschach',
  'Aurach',
  'Attersee',
  'Bodensee',
  'Donau',
  'Drau',
  'Erlaufsee',
  'Enns',
  'Faaker See',
  'Fuschlsee',
  'Gail',
  'Grabensee',
  'Grundlsee',
  'Gurk',
  'Haldensee',
  'Hallstätter See',
  'Heiterwanger See',
  'Hintersee',
  'Hintersteiner See',
  'Illmitzer Zicksee',
  'Inn',
  'Irrsee',
  'Kamp',
  'Keutschacher See',
  'Klopeiner See',
  'Lange Lacke',
  'Längsee',
  'Leitha',
  'Lunzer See',
  'March',
  'Mattsee',
  'Millstätter See',
  'Mondsee',
  'Mur',
  'Neufelder See',
  'Neusiedler See',
  'Obertrumer See',
  'Offensee',
  'Ossiacher See',
  'Plansee',
  'Pressegger See',
  'Raab',
  'Salzach',
  'Thaya',
  'Traun',
  'Traunsee',
  'Vilsalpsee',
  'Vorderer Gosausee',
  'Walchsee',
  'Wallersee',
  'Weissensee',
  'Wolfgangsee',
  'Wörthersee',
  'Ybbs',
  'Zeller See',
  'Zicksee'
];