<?php

return [
     // 🌊 Kärnten
       "Wörthersee" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Woerthersee.jpeg",
        "name" => "Wörthersee",
        "desc" => "Größter See Kärntens mit strukturreichen Buchten, Schilfkanten und tiefem Freiwasser. Sehr artenreich; gute Infrastruktur (Boote, Karten, Stege).",
        "fish" => [
            "Reinanke" => ["link" => "https://picsum.photos/200"],
            "Hecht"    => ["link" => "https://picsum.photos/200"],
            "Zander"   => ["link" => "https://picsum.photos/200"],
            "Karpfen"  => ["link" => "https://picsum.photos/200"],
            "Wels"     => ["link" => "https://picsum.photos/200"],
            "Barsch"   => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Reinanke","Hecht","Zander","Karpfen","Wels","Barsch","Schleie"],
        "tips" => "Frühjahr: flach an Schilfkanten auf Hecht (Jerkbait, Swimbait). Sommer: Renken mit Hegene über Kanten (12–20 m). Nacht: Zander mit Gummifisch/Jig an Steinpackungen; Boilies & Partikel für Karpfen in ruhigen Buchten.",
    ],
    "Ossiacher See" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Ossiachersee.jpeg",
        "name" => "Ossiacher See",
        "desc" => "Abwechslung pur zwischen Gerlitzen und Tauern: Schilf, Plateaus, Kanten bis ~50 m. Hecht, Zander, Karpfen, Renke, Barsch.",
        "fish" => [
            "Hecht"=>["link"=>"https://picsum.photos/200"], "Zander"=>["link"=>"https://picsum.photos/200"],
            "Karpfen"=>["link"=>"https://picsum.photos/200"], "Reinanke"=>["link"=>"https://picsum.photos/200"],
            "Wels"=>["link"=>"https://picsum.photos/200"], "Barsch"=>["link"=>"https://picsum.photos/200"],
        ],
        "reg_refs" => ["Hecht","Zander","Karpfen","Reinanke","Wels","Barsch","Schleie"],
        "tips" => "Zander ab Juni nachts an Hafenmauern/Drop-offs (3–8 m) mit Low-Action Shads. Hecht im Frühsommer in Krautfeldern mit Spinnerbait. Renke tagsüber mit feiner Hegene über Freiwasser-Schwärmen.",
    ],
    "Millstätter See" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Millstaettersee.jpeg",
        "name" => "Millstätter See",
        "desc" => "Tiefes Klarwassergewässer mit Reinanke und Seeforelle als Highlights; auch starke Hechte.",
        "fish" => [
            "Reinanke"=>["link"=>"https://picsum.photos/200"], "Seeforelle"=>["link"=>"https://picsum.photos/200"],
            "Hecht"=>["link"=>"https://picsum.photos/200"], "Karpfen"=>["link"=>"https://picsum.photos/200"],
            "Barsch"=>["link"=>"https://picsum.photos/200"],
        ],
        "reg_refs" => ["Reinanke","Seeforelle","Hecht","Karpfen","Barsch","Barsch"], // Barsch hat Ausnahmeregel (keine Schonzeit)
        "tips" => "Frühjahr/Spätherbst: Seeforelle mit Schleppködern (Wobbler, Blinkerlöffel) entlang Kanten. Renke: feine 0,12–0,16er, Hegene #16–18; Echolot hilfreich.",
    ],
    "Weißensee" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Weissensee.jpeg",
        "name" => "Weißensee",
        "desc" => "Höchstgelegener großer See Kärntens; sehr klar, kühl, salmonidenstark.",
        "fish" => [
            "Seeforelle"=>["link"=>"https://picsum.photos/200"], "Seesaibling"=>["link"=>"https://picsum.photos/200"],
            "Reinanke"=>["link"=>"https://picsum.photos/200"], "Hecht"=>["link"=>"https://picsum.photos/200"],
        ],
        "reg_refs" => ["Seeforelle","Seesaibling","Reinanke","Hecht","Barsch"],
        "tips" => "Früher Morgen: Saiblinge flacher (5–12 m) mit Naturköder (Wurm, Made) an feinen Montagen. Sommer: Seeforelle tiefer schleppen (Downrigger/Paravan).",
    ],
    "Faaker See" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Faakersee.jpeg",
        "name" => "Faaker See",
        "desc" => "Türkis, klar und sonnenreich – Barsche, Hechte und Renken.",
        "fish" => [
            "Renke"=>["link"=>"https://picsum.photos/200"], "Hecht"=>["link"=>"https://picsum.photos/200"],
            "Barsch"=>["link"=>"https://picsum.photos/200"], "Karpfen"=>["link"=>"https://picsum.photos/200"],
        ],
        "reg_refs" => ["Renke","Hecht","Barsch","Karpfen","Schleie"],
        "tips" => "Barsch: Microjigs/Drop-Shot an Steinrampen. Hecht: flach mit Jerkbait/fransenlosen Streamern an Krautkanten. Renke: Hegene im Mittelwasser über Tiefen.",
    ],
    "Klopeiner See" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Klopeinersee.jpeg",
        "name" => "Klopeiner See",
        "desc" => "Sehr warmes Sommergewässer – Zander, Hecht, Wels plus kräftige Friedfische.",
        "fish" => [
            "Zander"=>["link"=>"https://picsum.photos/200"], "Hecht"=>["link"=>"https://picsum.photos/200"],
            "Wels"=>["link"=>"https://picsum.photos/200"], "Karpfen"=>["link"=>"https://picsum.photos/200"],
            "Reinanke"=>["link"=>"https://picsum.photos/200"],
        ],
        "reg_refs" => ["Zander","Hecht","Wels","Karpfen","Reinanke","Schleie"],
        "tips" => "Sommernächte: Zander flach an Sandbänken (5–30 g Jigs, dunkle Shads). Wels: Großköder (Gummi 20–25 cm) in warmen Nächten an Kanten. Tags: Karpfen mit Partikel/Boilie.",
    ],
    "Pressegger See" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Presseggersee.jpeg",
        "name" => "Pressegger See",
        "desc" => "Flach, sonnig, viel Schilf – stark bei Friedfisch; Hecht/Barsch als Bonus.",
        "fish" => [
            "Karpfen"=>["link"=>"https://picsum.photos/200"], "Hecht"=>["link"=>"https://picsum.photos/200"],
            "Barsch"=>["link"=>"https://picsum.photos/200"], "Rotauge"=>["link"=>"https://picsum.photos/200"],
            "Rotfeder"=>["link"=>"https://picsum.photos/200"],
        ],
        "reg_refs" => ["Karpfen","Schleie","Hecht","Barsch","Rotauge","Rotfeder"],
        "tips" => "Karpfen: Randbereiche der Schilfinseln anfüttern; Method Feeder/Boilie. Hecht: Spinnerbait/Jerk über Kraut.",
    ],
    "Längsee" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Laengsee.jpeg",
        "name" => "Längsee",
        "desc" => "Ruhiges Naturgewässer mit Kraut- und Schilfzonen.",
        "fish" => [
            "Karpfen"=>["link"=>"https://picsum.photos/200"], "Schleie"=>["link"=>"https://picsum.photos/200"],
            "Hecht"=>["link"=>"https://picsum.photos/200"], "Wels"=>["link"=>"httpsum.photos/200"],
            "Barsch"=>["link"=>"https://picsum.photos/200"],
        ],
        "reg_refs" => ["Karpfen","Schleie","Hecht","Wels","Barsch"],
        "tips" => "Flachwasser im Frühsommer: Schleie auf Wurm/Mais. Hecht entlang Schilfkanten mit langsam geführten Softbaits.",
    ],
    "Brennsee" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Brennsee.jpeg",
        "name" => "Brennsee",
        "desc" => "Auch Feldsee; ruhige Buchten und Krautbänke, gemischter Bestand.",
        "fish" => [
            "Hecht"=>["link"=>"https://picsum.photos/200"], "Karpfen"=>["link"=>"https://picsum.photos/200"],
            "Renke"=>["link"=>"https://picsum.photos/200"], "Schleie"=>["link"=>"https://picsum.photos/200"],
            "Barsch"=>["link"=>"https://picsum.photos/200"],
        ],
        "reg_refs" => ["Hecht","Karpfen","Renke","Schleie","Barsch"],
        "tips" => "Sommer: Barsch mit kleinen Cranks an Stein-/Holzstrukturen. Abends: Hecht mit Topwater über Krautfeldern.",
    ],
    "Afritzer See" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Afritzersee.jpeg",
        "name" => "Afritzer See",
        "desc" => "Idyllischer Gegendtal-See; kurze Wege, viel Ruhe.",
        "fish" => [
            "Hecht"=>["link"=>"https://picsum.photos/200"], "Karpfen"=>["link"=>"https://picsum.photos/200"],
            "Barsch"=>["link"=>"https://picsum.photos/200"], "Rotauge"=>["link"=>"https://picsum.photos/200"],
            "Rotfeder"=>["link"=>"https://picsum.photos/200"],
        ],
        "reg_refs" => ["Hecht","Karpfen","Barsch","Schleie","Rotauge","Rotfeder"],
        "tips" => "Ufernah morgens: Barsch auf Drop-Shot. Karpfen tagsüber am Futterplatz (Method/Inline-Feeder).",
    ],
    "Urbansee" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Urbansee.jpeg",
        "name" => "Urbansee",
        "desc" => "Kleiner Waldsee; sehr friedfischlastig, punktuell Hecht.",
        "fish" => [
            "Karpfen"=>["link"=>"https://picsum.photos/200"], "Schleie"=>["link"=>"https://picsum.photos/200"],
            "Hecht"=>["link"=>"https://picsum.photos/200"], "Barsch"=>["link"=>"https://picsum.photos/200"],
        ],
        "reg_refs" => ["Karpfen","Schleie","Hecht","Barsch"],
        "tips" => "Leise präsentieren: Pole/Match & Brotflocke im Kraut; kleine Spinner #2 für Hecht-Trupps.",
    ],
    "Turnersee" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Turnersee.jpeg",
        "name" => "Turnersee",
        "desc" => "Warmer See im Jauntal; Naturparkumgebung, artenreich.",
        "fish" => [
            "Hecht"=>["link"=>"https://picsum.photos/200"], "Wels"=>["link"=>"https://picsum.photos/200"],
            "Karpfen"=>["link"=>"https://picsum.photos/200"], "Schleie"=>["link"=>"https://picsum.photos/200"],
            "Barsch"=>["link"=>"https://picsum.photos/200"],
        ],
        "reg_refs" => ["Hecht","Wels","Karpfen","Schleie","Barsch"],
        "tips" => "Sommernachtsfischen: Zupfermontage/Boilie auf Karpfen; Wels mit totem Köderfisch an Kanten & Ausläufen.",
    ],
    "Silbersee" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Silbersee.jpeg",
        "name" => "Silbersee",
        "desc" => "Stadtnaher Kurztrip-See bei Villach, viel Weißfisch.",
        "fish" => [
            "Rotauge"=>["link"=>"https://picsum.photos/200"], "Hecht"=>["link"=>"https://picsum.photos/200"],
            "Karpfen"=>["link"=>"https://picsum.photos/200"], "Barsch"=>["link"=>"https://picsum.photos/200"],
        ],
        "reg_refs" => ["Rotauge","Hecht","Karpfen","Barsch","Schleie"],
        "tips" => "Feedern mit süßen Mischungen, kleine Haken #12–16. Hecht im Herbst mit schlanken Jerkbaits entlang Steinpackungen.",
    ],
    "Maltschacher See" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Maltschachersee.jpeg",
        "name" => "Maltschacher See",
        "desc" => "Flach & warm, Camping-Umfeld; starke Friedfischzonen.",
        "fish" => [
            "Karpfen"=>["link"=>"https://picsum.photos/200"], "Schleie"=>["link"=>"https://picsum.photos/200"],
            "Hecht"=>["link"=>"https://picsum.photos/200"], "Barsch"=>["link"=>"https://picsum.photos/200"],
        ],
        "reg_refs" => ["Karpfen","Schleie","Hecht","Barsch","Rotauge","Rotfeder"],
        "tips" => "Frühjahr: Schleie auf Wurm/Mais in Krautfenstern. Karpfen: flach anfüttern, unauffällige Rigs.",
    ],
    "Keutschacher See" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Keutschachersee.jpeg",
        "name" => "Keutschacher See",
        "desc" => "Natursee im Seental; viel Kraut, Weißfisch, Karpfen, Schleie.",
        "fish" => [
            "Karpfen"=>["link"=>"https://picsum.photos/200"], "Schleie"=>["link"=>"https://picsum.photos/200"],
            "Hecht"=>["link"=>"https://picsum.photos/200"], "Rotauge"=>["link"=>"https://picsum.photos/200"],
        ],
        "reg_refs" => ["Karpfen","Schleie","Hecht","Rotauge","Barsch"],
        "tips" => "Unauffällige Präsentation im Klarwasser; Krautkanten systematisch absuchen (Texas/Weightless).",
    ],
    "Rauschelesee" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Rauschelesee.jpeg",
        "name" => "Rauschelesee",
        "desc" => "Kleiner, warmer See südlich des Wörthersees; Friedfischfokus.",
        "fish" => [
            "Karpfen"=>["link"=>"https://picsum.photos/200"], "Schleie"=>["link"=>"https://picsum.photos/200"],
            "Barsch"=>["link"=>"https://picsum.photos/200"],
        ],
        "reg_refs" => ["Karpfen","Schleie","Barsch","Hecht"],
        "tips" => "Leise Fütterung, kleine Köder. Barsch-Trupps mit Spinnern & kleinen Gummis absuchen.",
    ],
    "Gösselsdorfer See" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Goesselsdorfersee.jpeg",
        "name" => "Gösselsdorfer See",
        "desc" => "Sehr warm, flach, breite Schilfgürtel.",
        "fish" => [
            "Rotauge"=>["link"=>"https://picsum.photos/200"], "Hecht"=>["link"=>"https://picsum.photos/200"],
            "Karpfen"=>["link"=>"https://picsum.photos/200"], "Schleie"=>["link"=>"https://picsum.photos/200"],
        ],
        "reg_refs" => ["Rotauge","Hecht","Karpfen","Schleie","Barsch"],
        "tips" => "Hecht mit Spinnerbait über Kraut. Friedfisch mit Waggler weit über Schilfkehlen.",
    ],
    "Kraiger See" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Kraigersee.jpeg",
        "name" => "Kraiger See",
        "desc" => "Kleines, ruhiges Seengebiet; naturbelassen.",
        "fish" => [
            "Karpfen"=>["link"=>"https://picsum.photos/200"], "Schleie"=>["link"=>"https://picsum.photos/200"],
            "Rotauge"=>["link"=>"https://picsum.photos/200"],
        ],
        "reg_refs" => ["Karpfen","Schleie","Rotauge","Hecht"],
        "tips" => "Früh/Spät: Oberflächenaktivität beobachten; leichte Posenmontagen, Grundruten an Hotspots.",
    ],
    "Goggausee" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Goggausee.jpeg",
        "name" => "Goggausee",
        "desc" => "Waldsee bei Steuerberg; klar, ruhig.",
        "fish" => [
            "Karpfen"=>["link"=>"https://picsum.photos/200"], "Hecht"=>["link"=>"https://picsum.photos/200"],
            "Barsch"=>["link"=>"https://picsum.photos/200"],
        ],
        "reg_refs" => ["Karpfen","Hecht","Barsch","Schleie"],
        "tips" => "Hecht im Frühjahr flach; Barsch an Holz/Steg mit kleinen Jigs.",
    ],
    "Forstsee" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Forstsee.jpeg",
        "name" => "Forstsee",
        "desc" => "Stausee oberhalb des Wörthersees; kühles, klares Wasser.",
        "fish" => [
            "Regenbogenforelle"=>["link"=>"https://picsum.photos/200"], "Bachforelle"=>["link"=>"https://picsum.photos/200"],
            "Hecht"=>["link"=>"https://picsum.photos/200"], "Forellenbarsch"=>["link"=>"https://picsum.photos/200"],
        ],
        "reg_refs" => ["Regenbogenforelle","Bachforelle","Hecht","Forellenbarsch","Karpfen","Schleie","Zander","Wels"],
        "tips" => "Forelle: schlanke Wobbler/Spinner im Ejektionsbereich; Hecht mit Jerk/Jig an Felskanten. (Revier kann abweichende Maße/Zeiten vorgeben!)",
    ],
    "Hörzendorfer See" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Hoerzendorfersee.jpeg",
        "name" => "Hörzendorfer See",
        "desc" => "Zollfeld-See mit Flachwasser und Schilf.",
        "fish" => [
            "Karpfen"=>["link"=>"https://picsum.photos/200"], "Hecht"=>["link"=>"https://picsum.photos/200"],
            "Schleie"=>["link"=>"https://picsum.photos/200"],
        ],
        "reg_refs" => ["Karpfen","Hecht","Schleie","Barsch"],
        "tips" => "Karpfen: kurze Distanzen, unauffällige Rigs. Hecht: Krautbahnen mit Softjerks.",
    ],
    "St. Leonharder See" => [
        "state" => "Kärnten",
        "link" => "/images/waters/StLeonhardersee.jpeg",
        "name" => "St. Leonharder See",
        "desc" => "Kleines, ruhiges Gewässer nahe St. Veit.",
        "fish" => [
            "Karpfen"=>["link"=>"https://picsum.photos/200"], "Schleie"=>["link"=>"https://picsum.photos/200"],
            "Barsch"=>["link"=>"https://picsum.photos/200"],
        ],
        "reg_refs" => ["Karpfen","Schleie","Barsch","Hecht"],
        "tips" => "Frühmorgens: Posenfischen in Buchten; tagsüber: feine Grundmontagen.",
    ],
    "Hafnersee" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Hafnersee.jpeg",
        "name" => "Hafnersee",
        "desc" => "Natursee im Keutschacher Seental; sensible Schutzzonen.",
        "fish" => [
            "Karpfen"=>["link"=>"https://picsum.photos/200"], "Schleie"=>["link"=>"https://picsum.photos/200"],
            "Rotfeder"=>["link"=>"https://picsum.photos/200"], "Hecht"=>["link"=>"https://picsum.photos/200"],
        ],
        "reg_refs" => ["Karpfen","Schleie","Rotfeder","Hecht","Rotauge"],
        "tips" => "Krautlücken exakt anwerfen; Waathose meiden (Schutzzonen beachten).",
    ],
    "Vassacher See" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Vassachersee.jpeg",
        "name" => "Vassacher See",
        "desc" => "Stadtnah in Villach; warm & krautig.",
        "fish" => [
            "Rotauge"=>["link"=>"https://picsum.photos/200"], "Karpfen"=>["link"=>"https://picsum.photos/200"],
            "Hecht"=>["link"=>"https://picsum.photos/200"], "Barsch"=>["link"=>"https://picsum.photos/200"],
        ],
        "reg_refs" => ["Rotauge","Karpfen","Hecht","Barsch","Schleie"],
        "tips" => "Sommer: Oberflächenbisse auf Barsch (Topwater). Karpfen im Schatten der Schilfkanten.",
    ],
    "Sonnegger See" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Sonneggersee.jpeg",
        "name" => "Sonnegger See",
        "desc" => "Ruhiger See im Jauntal; weißfisch- & karpfenstark.",
        "fish" => [
            "Karpfen"=>["link"=>"https://picsum.photos/200"], "Schleie"=>["link"=>"https://picsum.photos/200"],
            "Hecht"=>["link"=>"https://picsum.photos/200"],
        ],
        "reg_refs" => ["Karpfen","Schleie","Hecht","Barsch"],
        "tips" => "Bodennahe, unauffällige Präsentation; kleine Köfis am Abend für Hecht.",
    ],
    "Magdalensee" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Magdalensee.jpeg",
        "name" => "Magdalensee",
        "desc" => "Kleiner See nahe Faaker See; warm & krautig.",
        "fish" => [
            "Rotfeder"=>["link"=>"https://picsum.photos/200"], "Rotauge"=>["link"=>"https://picsum.photos/200"],
            "Hecht"=>["link"=>"https://picsum.photos/200"], "Barsch"=>["link"=>"https://picsum.photos/200"],
        ],
        "reg_refs" => ["Rotfeder","Rotauge","Hecht","Barsch","Schleie"],
        "tips" => "Sommer: Waggler zwischen Krautbahnen; Hecht mit Weedless-Rigs.",
    ],
    "Flatschacher See" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Flatschachersee.jpeg",
        "name" => "Flatschacher See",
        "desc" => "Familienfreundlicher Badesee mit vielen Weißfischen.",
        "fish" => [
            "Karpfen"=>["link"=>"https://picsum.photos/200"], "Rotauge"=>["link"=>"https://picsum.photos/200"],
            "Schleie"=>["link"=>"https://picsum.photos/200"], "Hecht"=>["link"=>"https://picsum.photos/200"],
        ],
        "reg_refs" => ["Karpfen","Rotauge","Schleie","Hecht","Barsch"],
        "tips" => "Feeder & Method dicht am Schilfsaum; Hecht mit Spinner #4 an Kanten.",
    ],
    "St. Andräer See" => [
        "state" => "Kärnten",
        "link" => "/images/waters/StAndraeersee.jpeg",
        "name" => "St. Andräer See",
        "desc" => "Badesee im Lavanttal; unkompliziert zugänglich.",
        "fish" => [
            "Karpfen"=>["link"=>"https://picsum.photos/200"], "Schleie"=>["link"=>"https://picsum.photos/200"],
            "Barsch"=>["link"=>"https://picsum.photos/200"], "Hecht"=>["link"=>"https://picsum.photos/200"],
        ],
        "reg_refs" => ["Karpfen","Schleie","Barsch","Hecht","Rotauge"],
        "tips" => "Karpfen mit Partikelmischung vorbadender Bereiche; Barsch an Steganlagen.",
    ],
    "Drau" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Drau.jpeg",
        "name" => "Drau",
        "desc" => "Die Drau ist der wichtigste Fluss Kärntens und durchzieht Südösterreich.",
        "fish" => [
            "Äsche" => ["link" => "https://picsum.photos/200"],
            "Huchen" => ["link" => "https://picsum.photos/200"],
            "Barbe" => ["link" => "https://picsum.photos/200"],
        ],
    ],
    "Gail" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Gail.jpeg",
        "name" => "Drau",
        "desc" => "Die Drau ist der wichtigste Fluss Kärntens und durchzieht Südösterreich.",
        "fish" => [
            "Äsche" => ["link" => "https://picsum.photos/200"],
            "Huchen" => ["link" => "https://picsum.photos/200"],
            "Barbe" => ["link" => "https://picsum.photos/200"],
        ],
    ],
    "Millstätter See" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Millstättersee.jpeg",
        "name" => "Drau",
        "desc" => "Millstätte See",
        "fish" => [
            "Äsche" => ["link" => "https://picsum.photos/200"],
            "Huchen" => ["link" => "https://picsum.photos/200"],
            "Barbe" => ["link" => "https://picsum.photos/200"],
        ],
    ],
    
    // 🌊 Burgenland
    "Neusiedler See" => [
        "state" => "Burgenland",
        "link"  => "/images/waters/Neusiedler_See.jpeg",
        "name"  => "Neusiedler See",
        "desc"  => "Größter Steppensee Mitteleuropas (≈315 km²), UNESCO-Biosphärenpark, flach & schilfreich, geteilt mit Ungarn.",
        "fish"  => [
            "Reinanke" => ["link" => "https://picsum.photos/200"],
            "Hecht"    => ["link" => "https://picsum.photos/200"],
            "Zander"   => ["link" => "https://picsum.photos/200"],
            "Karpfen"  => ["link" => "https://picsum.photos/200"],
            "Wels"     => ["link" => "https://picsum.photos/200"],
            "Barsch"   => ["link" => "https://picsum.photos/200"],
            "Schleie"  => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Reinanke","Hecht","Zander","Karpfen","Wels","Barsch","Schleie"],
        "tips" => "Frühjahr: Hecht in Schilfbuchten (Spinnerbait/Swimbait). Sommer: Zander nachts an Kanten (Gummifisch). Karpfen im Schilf auf Partikel.",
    ],
    "Zicksee" => [
        "state" => "Burgenland",
        "link"  => "/images/waters/Zicksee.jpeg",
        "name"  => "Zicksee",
        "desc"  => "Flacher, periodischer Steppensee; Wasserstand schwankt stark, teils trockenfallend.",
        "fish"  => [
            "Hecht"    => ["link" => "https://picsum.photos/200"],
            "Karpfen"  => ["link" => "https://picsum.photos/200"],
            "Barsch"   => ["link" => "https://picsum.photos/200"],
            "Schleie"  => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Hecht","Karpfen","Barsch","Schleie"],
        "tips" => "Frühjahr flach an Schilfkanten; unauffällige Präsentationen wegen Klarwasser/Flachwasser.",
    ],
    "Lange Lacke" => [
        "state" => "Burgenland",
        "link"  => "/images/waters/Lange_Lacke.jpeg",
        "name"  => "Lange Lacke",
        "desc"  => "Periodische Lacke im Seewinkel; bedeutendes Vogelschutzgebiet (teils Schutzauflagen/Betretungsverbote beachten).",
        "fish"  => [],
        "reg_refs" => [],
        "tips" => "Naturschutz hat Vorrang; lokale Regelungen prüfen.",
    ],
    "Neufelder See" => [
        "state" => "Burgenland",
        "link"  => "/images/waters/Neufelder_See.jpeg",
        "name"  => "Neufelder See",
        "desc"  => "Klarer Baggersee; Bade- und Tauchrevier.",
        "fish"  => [
            "Hecht"    => ["link" => "https://picsum.photos/200"],
            "Zander"   => ["link" => "httpsum.photos/200"], // falls Tippfehler anpassen zu picsum
            "Karpfen"  => ["link" => "https://picsum.photos/200"],
            "Barsch"   => ["link" => "https://picsum.photos/200"],
            "Wels"     => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Hecht","Zander","Karpfen","Barsch","Wels"],
        "tips" => "Zander nachts an Stegen/Strukturen; tags Hecht an Kanten & Krautbetten.",
    ],

    // 🌊 Niederösterreich
    "Lunzer See" => [
        "state" => "Niederösterreich",
        "link"  => "/images/waters/Lunzer_See.jpeg",
        "name"  => "Lunzer See",
        "desc"  => "Einziger natürlicher See Niederösterreichs; klares Bergwasser in den Ybbstaler Alpen.",
        "fish"  => [
            "Reinanke"     => ["link" => "https://picsum.photos/200"],
            "Seeforelle"   => ["link" => "https://picsum.photos/200"],
            "Hecht"        => ["link" => "https://picsum.photos/200"],
            "Barsch"       => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Reinanke","Seeforelle","Hecht","Barsch"],
        "tips" => "Sommer: Renken mit Hegene 10–20 m. Frühjahr/Herbst: Hecht flacher an Schilf & Einläufen.",
    ],
    "Erlaufsee" => [
        "state" => "Niederösterreich",
        "link"  => "/images/waters/Erlaufsee.jpeg",
        "name"  => "Erlaufsee",
        "desc"  => "Klarer Grenzsee zu Steiermark; gute Sichtweiten, Bade- & Tauchsee.",
        "fish"  => [
            "Reinanke"     => ["link" => "https://picsum.photos/200"],
            "Seesaibling"  => ["link" => "https://picsum.photos/200"],
            "Seeforelle"   => ["link" => "https://picsum.photos/200"],
            "Hecht"        => ["link" => "https://picsum.photos/200"],
            "Barsch"       => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Reinanke","Seesaibling","Seeforelle","Hecht","Barsch"],
        "tips" => "Frühe Saison: Forellen an Kanten/Einläufen. Sommer: Renken tiefer (15–25 m).",
    ],
    "Ottensteiner Stausee" => [
        "state" => "Niederösterreich",
        "link"  => "/images/waters/Ottensteiner_Stausee.jpeg",
        "name"  => "Ottensteiner Stausee",
        "desc"  => "Fjordartige Granitlandschaft am Kamp; viele Buchten, Inseln, Klippen.",
        "fish"  => [
            "Hecht"   => ["link" => "https://picsum.photos/200"],
            "Zander"  => ["link" => "https://picsum.photos/200"],
            "Barsch"  => ["link" => "https://picsum.photos/200"],
            "Wels"    => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Hecht","Zander","Barsch","Wels"],
        "tips" => "Hecht an Felsabbrüchen (Jerkbait/Swimbait). Zander nachts an Steinpackungen mit Gummifisch.",
    ],
    "Dobra-Stausee" => [
        "state" => "Niederösterreich",
        "link"  => "/images/waters/Dobra_Stausee.jpeg",
        "name"  => "Dobra-Stausee",
        "desc"  => "Ruhige Stausee-Abschnitte, Paddel- und Kletter-Hotspot.",
        "fish"  => [
            "Hecht"  => ["link" => "https://picsum.photos/200"],
            "Zander" => ["link" => "https://picsum.photos/200"],
            "Barsch" => ["link" => "https://picsum.photos/200"],
            "Karpfen"=> ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Hecht","Zander","Barsch","Karpfen"],
        "tips" => "Sommerabends: Zander an Kanten. Hecht tagsüber an Holz & Fels.",
    ],
    "Thurnberger Stausee" => [
        "state" => "Niederösterreich",
        "link"  => "/images/waters/Thurnberger_Stausee.jpeg",
        "name"  => "Thurnberger Stausee",
        "desc"  => "Kamp-Stausee mit ausgedehnten Uferzonen und Kanten.",
        "fish"  => [
            "Hecht"  => ["link" => "https://picsum.photos/200"],
            "Zander" => ["link" => "https://picsum.photos/200"],
            "Barsch" => ["link" => "https://picsum.photos/200"],
            "Wels"   => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Hecht","Zander","Barsch","Wels"],
        "tips" => "Zander bei Dämmerung; Barsch truppweise an Steinpackungen (Jig/Minnow).",
    ],
    "Wienerwaldsee" => [
        "state" => "Niederösterreich",
        "link"  => "/images/waters/Wienerwaldsee.jpeg",
        "name"  => "Wienerwaldsee",
        "desc"  => "Speichersee mit Geschichte der Wiener Wasserversorgung; Ufer teils bewaldet.",
        "fish"  => [
            "Hecht"  => ["link" => "https://picsum.photos/200"],
            "Karpfen"=> ["link" => "https://picsum.photos/200"],
            "Barsch" => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Hecht","Karpfen","Barsch"],
        "tips" => "Frühjahr flach; Sommer nachts Karpfen mit Boilies in ruhigen Zonen.",
    ],

    // 🌊 Oberösterreich
    "Attersee" => [
        "state" => "Oberösterreich",
        "link"  => "/images/waters/Attersee.jpeg",
        "name"  => "Attersee",
        "desc"  => "Größter Binnen-See AT (≈46 km²), sehr klar, tiefe Kanten; Segeln & Tauchen.",
        "fish"  => [
            "Reinanke"     => ["link" => "https://picsum.photos/200"],
            "Seesaibling"  => ["link" => "https://picsum.photos/200"],
            "Hecht"        => ["link" => "https://picsum.photos/200"],
            "Zander"       => ["link" => "https://picsum.photos/200"],
            "Barsch"       => ["link" => "https://picsum.photos/200"],
            "Karpfen"      => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Reinanke","Seesaibling","Hecht","Zander","Barsch","Karpfen"],
        "tips" => "Renken im Sommer 15–25 m (Hegene). Hecht im Frühjahr flach; Zander nachts an Steinpackungen.",
    ],
    "Traunsee" => [
        "state" => "Oberösterreich",
        "link"  => "/images/waters/Traunsee.jpeg",
        "name"  => "Traunsee",
        "desc"  => "Sehr tief (bis ~191 m), fjordartige Ufer, klares Wasser.",
        "fish"  => [
            "Reinanke"     => ["link" => "https://picsum.photos/200"],
            "Seesaibling"  => ["link" => "https://picsum.photos/200"],
            "Seeforelle"   => ["link" => "https://picsum.photos/200"],
            "Hecht"        => ["link" => "https://picsum.photos/200"],
            "Barsch"       => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Reinanke","Seesaibling","Seeforelle","Hecht","Barsch"],
        "tips" => "Forellen/ Saibling tief über Kanten schleppen; Renken vertikal.",
    ],
    "Mondsee" => [
        "state" => "Oberösterreich",
        "link"  => "/images/waters/Mondsee.jpeg",
        "name"  => "Mondsee",
        "desc"  => "Karstsee, klare Sicht, markante Uferkanten.",
        "fish"  => [
            "Reinanke"     => ["link" => "https://picsum.photos/200"],
            "Hecht"        => ["link" => "https://picsum.photos/200"],
            "Zander"       => ["link" => "https://picsum.photos/200"],
            "Barsch"       => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Reinanke","Hecht","Zander","Barsch"],
        "tips" => "Hecht im Frühjahr flach; Renken im Sommer tiefer mit Hegene.",
    ],
    "Wolfgangsee (OO Anteil)" => [
        "state" => "Oberösterreich",
        "link"  => "/images/waters/Wolfgangsee_OO_Anteil.jpeg",
        "name"  => "Wolfgangsee",
        "desc"  => "Grenzsee zu Salzburg; klare Buchten und Steilufer.",
        "fish"  => [
            "Reinanke"    => ["link" => "https://picsum.photos/200"],
            "Hecht"       => ["link" => "https://picsum.photos/200"],
            "Barsch"      => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Reinanke","Hecht","Barsch"],
        "tips" => "Renken über Kanten; Hecht in Kraut- und Schilfzonen.",
    ],
    "Hallstätter See" => [
        "state" => "Oberösterreich",
        "link"  => "/images/waters/Hallstaetter_See.jpeg",
        "name"  => "Hallstätter See",
        "desc"  => "UNESCO-Kulisse, kaltes, klares Wasser; tiefe Ufer.",
        "fish"  => [
            "Reinanke"    => ["link" => "https://picsum.photos/200"],
            "Seesaibling" => ["link" => "https://picsum.photos/200"],
            "Seeforelle"  => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Reinanke","Seesaibling","Seeforelle"],
        "tips" => "Schleppen auf Forelle/ Saibling entlang tiefer Kanten; Renken vertikal.",
    ],
    "Irrsee" => [
        "state" => "Oberösterreich",
        "link"  => "/images/waters/Irrsee.jpeg",
        "name"  => "Irrsee (Zeller See)",
        "desc"  => "Relativ warm; Flachwasserzonen mit Krautgürteln.",
        "fish"  => [
            "Hecht"   => ["link" => "https://picsum.photos/200"],
            "Karpfen" => ["link" => "https://picsum.photos/200"],
            "Barsch"  => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Hecht","Karpfen","Barsch"],
        "tips" => "Hecht flach im Frühjahr; Karpfen in Buchten (Boilies/Partikel).",
    ],
    "Almsee" => [
        "state" => "Oberösterreich",
        "link"  => "/images/waters/Almsee.jpeg",
        "name"  => "Almsee",
        "desc"  => "Türkisgrüner Bergsee im Naturschutzgebiet; sehr klar.",
        "fish"  => [
            "Seeforelle" => ["link" => "https://picsum.photos/200"],
            "Barsch"     => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Seeforelle","Barsch"],
        "tips" => "Klares Wasser: feine Vorfächer und natürliche Köderfarben.",
    ],
    "Vorderer Gosausee" => [
        "state" => "Oberösterreich",
        "link"  => "/images/waters/Vorderer_Gosausee.jpeg",
        "name"  => "Vorderer Gosausee",
        "desc"  => "Sehr klarer Bergsee; Dachsteinblick.",
        "fish"  => [
            "Seeforelle" => ["link" => "https://picsum.photos/200"],
            "Saibling"   => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Seeforelle","Saibling"],
        "tips" => "Leichte Rigs, unauffällige Präsentation, frühe/ späte Tageszeiten.",
    ],
    "Hinterer Gosausee" => [
        "state" => "Oberösterreich",
        "link"  => "/images/waters/Hinterer_Gosausee.jpeg",
        "name"  => "Hinterer Gosausee",
        "desc"  => "Abgelegener Bergsee; glasklar.",
        "fish"  => [
            "Seeforelle" => ["link" => "https://picsum.photos/200"],
            "Saibling"   => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Seeforelle","Saibling"],
        "tips" => "Still & klar – weite Würfe, feines Gerät.",
    ],
    "Vorderer Langbathsee" => [
        "state" => "Oberösterreich",
        "link"  => "/images/waters/Vorderer_Langbathsee.jpeg",
        "name"  => "Vorderer Langbathsee",
        "desc"  => "Klarer Bergsee nahe Ebensee.",
        "fish"  => [
            "Seeforelle" => ["link" => "https://picsum.photos/200"],
            "Saibling"   => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Seeforelle","Saibling"],
        "tips" => "Früh & spät aktiv; Schlauchboote/ Belly (falls erlaubt) vorteilhaft.",
    ],
    "Hinterer Langbathsee" => [
        "state" => "Oberösterreich",
        "link"  => "/images/waters/Hinterer_Langbathsee.jpeg",
        "name"  => "Hinterer Langbathsee",
        "desc"  => "Kleiner, klarer Bergsee im Waldkessel.",
        "fish"  => [
            "Seeforelle" => ["link" => "https://picsum.photos/200"],
            "Saibling"   => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Seeforelle","Saibling"],
        "tips" => "Unauffällige Montagen; Uferpirsch.",
    ],

    // 🌊 Salzburg
    "Zeller See" => [
        "state" => "Salzburg",
        "link"  => "/images/waters/Zeller_See.jpeg",
        "name"  => "Zeller See",
        "desc"  => "Alpiner, klarer Badesee mit Gletscherblick.",
        "fish"  => [
            "Reinanke"   => ["link" => "https://picsum.photos/200"],
            "Seeforelle" => ["link" => "https://picsum.photos/200"],
            "Hecht"      => ["link" => "https://picsum.photos/200"],
            "Karpfen"    => ["link" => "https://picsum.photos/200"],
            "Barsch"     => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Reinanke","Seeforelle","Hecht","Karpfen","Barsch"],
        "tips" => "Frühjahr: Forelle an Kanten/Einläufen. Sommer: Renken 10–20 m (Hegene).",
    ],
    "Wallersee" => [
        "state" => "Salzburg",
        "link"  => "/images/waters/Wallersee.jpeg",
        "name"  => "Wallersee",
        "desc"  => "Relativ flach, windoffen; ausgedehnte Schilfzonen.",
        "fish"  => [
            "Hecht"   => ["link" => "https://picsum.photos/200"],
            "Zander"  => ["link" => "https://picsum.photos/200"],
            "Karpfen" => ["link" => "https://picsum.photos/200"],
            "Barsch"  => ["link" => "https://picsum.photos/200"],
            "Wels"    => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Hecht","Zander","Karpfen","Barsch","Wels"],
        "tips" => "Hecht im Frühjahr in Schilfbuchten; Zander nachts an Kanten.",
    ],
    "Mattsee" => [
        "state" => "Salzburg",
        "link"  => "/images/waters/Mattsee.jpeg",
        "name"  => "Mattsee",
        "desc"  => "Teil der Trumer Seen; strukturreiche Ufer mit Schilf & Buchten.",
        "fish"  => [
            "Hecht"   => ["link" => "https://picsum.photos/200"],
            "Zander"  => ["link" => "https://picsum.photos/200"],
            "Barsch"  => ["link" => "https://picsum.photos/200"],
            "Karpfen" => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Hecht","Zander","Barsch","Karpfen"],
        "tips" => "Frühsommer: Hecht im Kraut; Barsch an Steinpackungen (Jig/Crank).",
    ],
    "Obertrumer See" => [
        "state" => "Salzburg",
        "link"  => "/images/waters/Obertrumer_See.jpeg",
        "name"  => "Obertrumer See",
        "desc"  => "Größter der Trumer Seen; weiträumige Flachwasserbereiche.",
        "fish"  => [
            "Hecht"   => ["link" => "https://picsum.photos/200"],
            "Zander"  => ["link" => "https://picsum.photos/200"],
            "Barsch"  => ["link" => "https://picsum.photos/200"],
            "Karpfen" => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Hecht","Zander","Barsch","Karpfen"],
        "tips" => "Abend-/Nacht: Zander an Übergängen von Flach- zu Tiefwasser.",
    ],
    "Grabensee" => [
        "state" => "Salzburg",
        "link"  => "/images/waters/Grabensee.jpeg",
        "name"  => "Grabensee",
        "desc"  => "Kleiner, naturnaher Teil der Trumer Seen; Schilfgürtel.",
        "fish"  => [
            "Hecht"   => ["link" => "https://picsum.photos/200"],
            "Barsch"  => ["link" => "https://picsum.photos/200"],
            "Karpfen" => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Hecht","Barsch","Karpfen"],
        "tips" => "Hecht in Buchten; Barsch an Schilfkanten mit leichten Jigs.",
    ],
    "Fuschlsee" => [
        "state" => "Salzburg",
        "link"  => "/images/waters/Fuschlsee.jpeg",
        "name"  => "Fuschlsee",
        "desc"  => "Sehr klares Wasser, Uferwanderweg; steile Kanten.",
        "fish"  => [
            "Reinanke"   => ["link" => "https://picsum.photos/200"],
            "Seeforelle" => ["link" => "https://picsum.photos/200"],
            "Hecht"      => ["link" => "https://picsum.photos/200"],
            "Barsch"     => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Reinanke","Seeforelle","Hecht","Barsch"],
        "tips" => "Tagesrandzeiten & feine Vorfächer; Renken tiefer im Sommer.",
    ],
    "Hintersee Faistenau" => [
        "state" => "Salzburg",
        "link"  => "/images/waters/Hintersee_Faistenau.jpeg",
        "name"  => "Hintersee (Faistenau)",
        "desc"  => "Kleiner, klarer Bergsee; familienfreundlich.",
        "fish"  => [
            "Seeforelle" => ["link" => "https://picsum.photos/200"],
            "Barsch"     => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Seeforelle","Barsch"],
        "tips" => "Leichte Rigs; kleine Minnows/Spinner.",
    ],
    "Wolfgangsee (Sbg Anteil)" => [
        "state" => "Salzburg",
        "link"  => "/images/waters/Wolfgangsee_Sbg_Anteil.jpeg",
        "name"  => "Wolfgangsee",
        "desc"  => "Grenzsee zu Oberösterreich; klare Buchten, touristische Infrastruktur.",
        "fish"  => [
            "Reinanke" => ["link" => "https://picsum.photos/200"],
            "Hecht"    => ["link" => "https://picsum.photos/200"],
            "Barsch"   => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Reinanke","Hecht","Barsch"],
        "tips" => "Renken über Kanten, Hecht im Krautgürtel.",
    ],

    // 🌊 Steiermark
    "Grundlsee" => [
        "state" => "Steiermark",
        "link"  => "/images/waters/Grundlsee.jpeg",
        "name"  => "Grundlsee",
        "desc"  => "‚Steirisches Meer‘; großer Klarwassersee im Ausseerland.",
        "fish"  => [
            "Reinanke"    => ["link" => "https://picsum.photos/200"],
            "Seesaibling" => ["link" => "https://picsum.photos/200"],
            "Hecht"       => ["link" => "https://picsum.photos/200"],
            "Barsch"      => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Reinanke","Seesaibling","Hecht","Barsch"],
        "tips" => "Sommer: Renken tiefer (Hegene). Hecht an Kraut- & Schilfkanten.",
    ],
    "Altausseer See" => [
        "state" => "Steiermark",
        "link"  => "/images/waters/Altausseer_See.jpeg",
        "name"  => "Altausseer See",
        "desc"  => "Smaragdgrüner, klarer See am Loser; steile Ufer.",
        "fish"  => [
            "Reinanke"   => ["link" => "https://picsum.photos/200"],
            "Seesaibling"=> ["link" => "https://picsum.photos/200"],
            "Seeforelle" => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Reinanke","Seesaibling","Seeforelle"],
        "tips" => "Feine Hegenen/Fliegen; Schleppangeln tief an Kanten.",
    ],
    "Toplitzsee" => [
        "state" => "Steiermark",
        "link"  => "/images/waters/Toplitzsee.jpeg",
        "name"  => "Toplitzsee",
        "desc"  => "Mystisch, meromiktisch; beschränkter Zugang/Schutzauflagen.",
        "fish"  => [
            "Saibling"   => ["link" => "https://picsum.photos/200"],
            "Seeforelle" => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Saibling","Seeforelle"],
        "tips" => "Vorab lokale Bestimmungen genau prüfen.",
    ],
    "Erlaufsee (Stmk Anteil)" => [
        "state" => "Steiermark",
        "link"  => "/images/waters/Erlaufsee_Stmk_Anteil.jpeg",
        "name"  => "Erlaufsee (Stmk-Anteil)",
        "desc"  => "Klarer Grenzsee zu Niederösterreich.",
        "fish"  => [
            "Reinanke"     => ["link" => "https://picsum.photos/200"],
            "Seesaibling"  => ["link" => "https://picsum.photos/200"],
            "Seeforelle"   => ["link" => "https://picsum.photos/200"],
            "Hecht"        => ["link" => "https://picsum.photos/200"],
            "Barsch"       => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Reinanke","Seesaibling","Seeforelle","Hecht","Barsch"],
        "tips" => "Ähnlich NÖ-Seite: Renken tiefer, Forellen an Kanten.",
    ],
    "Leopoldsteiner See" => [
        "state" => "Steiermark",
        "link"  => "/images/waters/Leopoldsteiner_See.jpeg",
        "name"  => "Leopoldsteiner See",
        "desc"  => "Bergsee bei Eisenerz; grün-türkises Wasser.",
        "fish"  => [
            "Seeforelle" => ["link" => "https://picsum.photos/200"],
            "Saibling"   => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Seeforelle","Saibling"],
        "tips" => "Leichte Spinn-/Fliegenruten; unauffällige Farben.",
    ],
    "Stubenbergsee" => [
        "state" => "Steiermark",
        "link"  => "/images/waters/Stubenbergsee.jpeg",
        "name"  => "Stubenbergsee",
        "desc"  => "Künstlicher Badesee im Hügelland; Freizeitangebot.",
        "fish"  => [
            "Karpfen" => ["link" => "https://picsum.photos/200"],
            "Barsch"  => ["link" => "https://picsum.photos/200"],
            "Hecht"   => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Karpfen","Barsch","Hecht"],
        "tips" => "Karpfen an Futterplätzen; leichte Gummis auf Barsch.",
    ],
    "Schwarzlsee" => [
        "state" => "Steiermark",
        "link"  => "/images/waters/Schwarzlsee.jpeg",
        "name"  => "Schwarzlsee",
        "desc"  => "Baggersee bei Graz; Events & Freizeit.",
        "fish"  => [
            "Karpfen" => ["link" => "https://picsum.photos/200"],
            "Wels"    => ["link" => "https://picsum.photos/200"],
            "Barsch"  => ["link" => "https://picsum.photos/200"],
            "Hecht"   => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Karpfen","Wels","Barsch","Hecht"],
        "tips" => "Warmwasserzeiten: Wels nachts; Karpfen an Ruten mit Partikel/Boilies.",
    ],
    "Thalersee" => [
        "state" => "Steiermark",
        "link"  => "/images/waters/Thalersee.jpeg",
        "name"  => "Thalersee",
        "desc"  => "Kleiner Stausee westlich von Graz; Naherholung.",
        "fish"  => [
            "Karpfen" => ["link" => "https://picsum.photos/200"],
            "Barsch"  => ["link" => "https://picsum.photos/200"],
            "Hecht"   => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Karpfen","Barsch","Hecht"],
        "tips" => "Barsch an Holz/Strukturen; Karpfen in ruhigen Buchten.",
    ],
    "Teichalmsee" => [
        "state" => "Steiermark",
        "link"  => "/images/waters/Teichalmsee.jpeg",
        "name"  => "Teichalmsee",
        "desc"  => "Kleiner Hochalmsee mit moorigem Charakter.",
        "fish"  => [
            "Barsch"  => ["link" => "https://picsum.photos/200"],
            "Forelle" => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Barsch","Forelle"],
        "tips" => "Kleinere Köder; Ufernah in den Tagesrandzeiten.",
    ],

    // 🌊 Tirol
    "Achensee" => [
        "state" => "Tirol",
        "link"  => "/images/waters/Achensee.jpeg",
        "name"  => "Achensee",
        "desc"  => "Größter See Tirols; windsicher, klares Tiefwasser.",
        "fish"  => [
            "Reinanke"    => ["link" => "https://picsum.photos/200"],
            "Seesaibling" => ["link" => "https://picsum.photos/200"],
            "Seeforelle"  => ["link" => "https://picsum.photos/200"],
            "Hecht"       => ["link" => "https://picsum.photos/200"],
            "Barsch"      => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Reinanke","Seesaibling","Seeforelle","Hecht","Barsch"],
        "tips" => "Renken/ Saiblinge tief (Sommer). Hecht an Kanten & Buchten im Frühjahr.",
    ],
    "Plansee" => [
        "state" => "Tirol",
        "link"  => "/images/waters/Plansee.jpeg",
        "name"  => "Plansee",
        "desc"  => "Klarer, tiefer See; Verbindung zum Heiterwanger See.",
        "fish"  => [
            "Seeforelle"  => ["link" => "https://picsum.photos/200"],
            "Seesaibling" => ["link" => "https://picsum.photos/200"],
            "Hecht"       => ["link" => "https://picsum.photos/200"],
            "Barsch"      => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Seeforelle","Seesaibling","Hecht","Barsch"],
        "tips" => "Schleppen entlang Steilkanten; Barsch auf Jigs an Felsstrukturen.",
    ],
    "Heiterwanger See" => [
        "state" => "Tirol",
        "link"  => "/images/waters/Heiterwanger_See.jpeg",
        "name"  => "Heiterwanger See",
        "desc"  => "Mit Plansee verbunden; klare Buchten.",
        "fish"  => [
            "Seeforelle"  => ["link" => "https://picsum.photos/200"],
            "Hecht"       => ["link" => "https://picsum.photos/200"],
            "Barsch"      => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Seeforelle","Hecht","Barsch"],
        "tips" => "Frühjahr: Hecht flach; Sommer: Forellen tiefer an Drops.",
    ],
    "Walchsee" => [
        "state" => "Tirol",
        "link"  => "/images/waters/Walchsee.jpeg",
        "name"  => "Walchsee",
        "desc"  => "Wärmerer Badesee, krautreiche Flachwasserzonen.",
        "fish"  => [
            "Hecht"   => ["link" => "https://picsum.photos/200"],
            "Karpfen" => ["link" => "https://picsum.photos/200"],
            "Barsch"  => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Hecht","Karpfen","Barsch"],
        "tips" => "Hecht im Kraut (Spinnerbait/Swimbait); Karpfen an Futterplätzen.",
    ],
    "Piburger See" => [
        "state" => "Tirol",
        "link"  => "/images/waters/Piburger_See.jpeg",
        "name"  => "Piburger See",
        "desc"  => "Warmes Sommerwasser, Naturdenkmal; kleiner Bergsee.",
        "fish"  => [
            "Hecht"  => ["link" => "https://picsum.photos/200"],
            "Barsch" => ["link" => "https://picsum.photos/200"],
            "Karpfen"=> ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Hecht","Barsch","Karpfen"],
        "tips" => "Kleine Boote/ Belly (wenn erlaubt); unauffällige Präsentation.",
    ],
    "Haldensee" => [
        "state" => "Tirol",
        "link"  => "/images/waters/Haldensee.jpeg",
        "name"  => "Haldensee",
        "desc"  => "Tannheimer Tal; klare Uferzonen.",
        "fish"  => [
            "Hecht"  => ["link" => "https://picsum.photos/200"],
            "Barsch" => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Hecht","Barsch"],
        "tips" => "Hecht in Krautgürteln; Barsch mit kleinen Gummis.",
    ],
    "Vilsalpsee" => [
        "state" => "Tirol",
        "link"  => "/images/waters/Vilsalpsee.jpeg",
        "name"  => "Vilsalpsee",
        "desc"  => "Naturschutzgebiet; klare, kühle Bedingungen.",
        "fish"  => [
            "Forelle" => ["link" => "https://picsum.photos/200"],
            "Saibling"=> ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Forelle","Saibling"],
        "tips" => "Regelungen/Schonzeiten streng beachten; feine Rigs.",
    ],
    "Hintersteiner See" => [
        "state" => "Tirol",
        "link"  => "/images/waters/Hintersteiner_See.jpeg",
        "name"  => "Hintersteiner See",
        "desc"  => "Kleiner, sehr klarer See am Wilden Kaiser.",
        "fish"  => [
            "Forelle" => ["link" => "https://picsum.photos/200"],
            "Saibling"=> ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Forelle","Saibling"],
        "tips" => "Unauffällige Farben; leise Uferpirsch.",
    ],
    "Reintaler See" => [
        "state" => "Tirol",
        "link"  => "/images/waters/Reintaler_See.jpeg",
        "name"  => "Reintaler See",
        "desc"  => "Teil der Kramsacher Seenplatte.",
        "fish"  => [
            "Karpfen" => ["link" => "https://picsum.photos/200"],
            "Hecht"   => ["link" => "https://picsum.photos/200"],
            "Barsch"  => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Karpfen","Hecht","Barsch"],
        "tips" => "Karpfen an Schilf; Hecht in Buchten.",
    ],
    "Krummsee" => [
        "state" => "Tirol",
        "link"  => "/images/waters/Krummsee.jpeg",
        "name"  => "Krummsee",
        "desc"  => "Kramsacher Seenplatte; klein & klar.",
        "fish"  => [
            "Karpfen" => ["link" => "https://picsum.photos/200"],
            "Barsch"  => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Karpfen","Barsch"],
        "tips" => "Feines Gerät; kleine Wobbler/Softbaits.",
    ],
    "Berglsteiner See" => [
        "state" => "Tirol",
        "link"  => "/images/waters/Berglsteiner_See.jpeg",
        "name"  => "Berglsteiner See",
        "desc"  => "Kleiner, idyllischer See in der Seenplatte.",
        "fish"  => [
            "Barsch"  => ["link" => "https://picsum.photos/200"],
            "Karpfen" => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Barsch","Karpfen"],
        "tips" => "Ufernah, leichte Rigs.",
    ],
    "Schwarzsee Kitzbuehel" => [
        "state" => "Tirol",
        "link"  => "/images/waters/Schwarzsee_Kitzbuehel.jpeg",
        "name"  => "Schwarzsee (Kitzbühel)",
        "desc"  => "Mooriger Badesee, warm; Krautgürtel & Flachwasser.",
        "fish"  => [
            "Hecht"   => ["link" => "https://picsum.photos/200"],
            "Karpfen" => ["link" => "https://picsum.photos/200"],
            "Barsch"  => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Hecht","Karpfen","Barsch"],
        "tips" => "Hecht im Kraut (Spinnerbait). Karpfen an ruhigen Uferabschnitten.",
    ],
    "Wildsee Seefeld" => [
        "state" => "Tirol",
        "link"  => "/images/waters/Wildsee_Seefeld.jpeg",
        "name"  => "Wildsee (Seefeld)",
        "desc"  => "Moor-/Badesee; Promenade & Freizeitnutzung.",
        "fish"  => [
            "Hecht"  => ["link" => "https://picsum.photos/200"],
            "Barsch" => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Hecht","Barsch"],
        "tips" => "Frühjahr/Herbst: Hecht flach; Sommer: Barsch mit kleinen Jigs.",
    ],

    // 🌊 Vorarlberg
    "Bodensee AT Anteil" => [
        "state" => "Vorarlberg",
        "link"  => "/images/waters/Bodensee_AT_Anteil.jpeg",
        "name"  => "Bodensee (AT-Anteil)",
        "desc"  => "Internationaler See (DE/AT/CH); weite Flächen, Häfen, Strukturen.",
        "fish"  => [
            "Felchen"  => ["link" => "https://picsum.photos/200"], // Felchen = Reinanke/Maräne je nach Nomenklatur
            "Hecht"    => ["link" => "https://picsum.photos/200"],
            "Zander"   => ["link" => "https://picsum.photos/200"],
            "Barsch"   => ["link" => "https://picsum.photos/200"],
            "Wels"     => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Felchen","Hecht","Zander","Barsch","Wels"],
        "tips" => "Felchen mit Hegene (tief). Zander nachts an Steinpackungen/Spundwänden.",
    ],
    "Lünersee" => [
        "state" => "Vorarlberg",
        "link"  => "/images/waters/Luenersee.jpeg",
        "name"  => "Lünersee",
        "desc"  => "Hochgebirgs-Speichersee im Rätikon; markante Farbe.",
        "fish"  => [
            "Saibling" => ["link" => "https://picsum.photos/200"],
            "Forelle"  => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Saibling","Forelle"],
        "tips" => "Bergsee-typisch: feine Montagen, natürliche Farben.",
    ],
    "Silvretta-Stausee" => [
        "state" => "Vorarlberg",
        "link"  => "/images/waters/Silvretta_Stausee.jpeg",
        "name"  => "Silvretta-Stausee",
        "desc"  => "Hochgebirgsstausee; kühle Bedingungen.",
        "fish"  => [
            "Saibling" => ["link" => "https://picsum.photos/200"],
            "Forelle"  => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Saibling","Forelle"],
        "tips" => "Wasserspiegelschwankungen beachten; tiefer fischen.",
    ],
    "Vermuntsee" => [
        "state" => "Vorarlberg",
        "link"  => "/images/waters/Vermuntsee.jpeg",
        "name"  => "Vermuntsee",
        "desc"  => "Stausee oberhalb Partenen; kaltes, klares Wasser.",
        "fish"  => [
            "Saibling" => ["link" => "https://picsum.photos/200"],
            "Forelle"  => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Saibling","Forelle"],
        "tips" => "Kompakte Blinker/Wobbler; tiefe Zonen abklopfen.",
    ],
    "Kopssee" => [
        "state" => "Vorarlberg",
        "link"  => "/images/waters/Kopssee.jpeg",
        "name"  => "Kopssee",
        "desc"  => "Hochgebirgsstausee der Illwerke.",
        "fish"  => [
            "Saibling" => ["link" => "https://picsum.photos/200"],
            "Forelle"  => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Saibling","Forelle"],
        "tips" => "Früh/Spät am besten; tiefe Bereiche im Sommer.",
    ],
    "Spullersee" => [
        "state" => "Vorarlberg",
        "link"  => "/images/waters/Spullersee.jpeg",
        "name"  => "Spullersee",
        "desc"  => "Speichersee im Lechquellengebirge.",
        "fish"  => [
            "Saibling" => ["link" => "https://picsum.photos/200"],
            "Forelle"  => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Saibling","Forelle"],
        "tips" => "Natürliche Muster; Uferwechsel je nach Wind/Sonne.",
    ],
    "Formarinsee" => [
        "state" => "Vorarlberg",
        "link"  => "/images/waters/Formarinsee.jpeg",
        "name"  => "Formarinsee",
        "desc"  => "Speichersee nahe der Roten Wand; Ausgangspunkt beliebter Touren.",
        "fish"  => [
            "Saibling" => ["link" => "https://picsum.photos/200"],
            "Forelle"  => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Saibling","Forelle"],
        "tips" => "Feine Rigs; Wetterumschwünge im Hochgebirge beachten.",
    ],
    "Seewaldsee" => [
        "state" => "Vorarlberg",
        "link"  => "/images/waters/Seewaldsee.jpeg",
        "name"  => "Seewaldsee",
        "desc"  => "Kleiner Natursee im Großen Walsertal.",
        "fish"  => [
            "Forelle" => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Forelle"],
        "tips" => "Kleine Spinner/Wobbler; vorsichtiges Anpirschen.",
    ],
    "Körbersee" => [
        "state" => "Vorarlberg",
        "link"  => "/images/waters/Koerbersee.jpeg",
        "name"  => "Körbersee",
        "desc"  => "Sehr idyllischer Bergsee (Lechquellengebiet).",
        "fish"  => [
            "Forelle" => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Forelle"],
        "tips" => "Feines Tackle, klare Bedingungen.",
    ],
    "Kalbelesee" => [
        "state" => "Vorarlberg",
        "link"  => "/images/waters/Kalbelesee.jpeg",
        "name"  => "Kalbelesee",
        "desc"  => "Kleiner See nahe dem Körbersee.",
        "fish"  => [
            "Forelle" => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Forelle"],
        "tips" => "Kompakte, kleine Köder; leise angehen.",
    ],

    // 🌊 Wien
    "Alte Donau" => [
        "state" => "Wien",
        "link"  => "/images/waters/Alte_Donau.jpeg",
        "name"  => "Alte Donau",
        "desc"  => "Ehemaliger Donau-Altarm; heute stehendes Gewässer mit Bädern/Stegen.",
        "fish"  => [
            "Hecht"   => ["link" => "https://picsum.photos/200"],
            "Zander"  => ["link" => "https://picsum.photos/200"],
            "Karpfen" => ["link" => "https://picsum.photos/200"],
            "Barsch"  => ["link" => "https://picsum.photos/200"],
            "Wels"    => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Hecht","Zander","Karpfen","Barsch","Wels"],
        "tips" => "Zander nachts an Stein-/Spundwänden; Hecht im Kraut & an Stegen.",
    ],
    "Neue Donau" => [
        "state" => "Wien",
        "link"  => "/images/waters/Neue_Donau.jpeg",
        "name"  => "Neue Donau",
        "desc"  => "Entlastungsgerinne, aber als Bade-/Angelgewässer genutzt; kanalartige Strukturen.",
        "fish"  => [
            "Zander"  => ["link" => "https://picsum.photos/200"],
            "Wels"    => ["link" => "https://picsum.photos/200"],
            "Barsch"  => ["link" => "https://picsum.photos/200"],
            "Hecht"   => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Zander","Wels","Barsch","Hecht"],
        "tips" => "Zander in der Dämmerung an Kanten; Wels nachts großvolumig.",
    ],
    "Kaiserwasser" => [
        "state" => "Wien",
        "link"  => "/images/waters/Kaiserwasser.jpeg",
        "name"  => "Kaiserwasser",
        "desc"  => "Seitenarm/Altarm an der Donau City; ruhige Zonen.",
        "fish"  => [
            "Hecht"   => ["link" => "https://picsum.photos/200"],
            "Barsch"  => ["link" => "https://picsum.photos/200"],
            "Karpfen" => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Hecht","Barsch","Karpfen"],
        "tips" => "Tagsüber Barsch an Stegen; Hecht morgens/abends an Kraut.",
    ],
    "Badeteich Hirschstetten" => [
        "state" => "Wien",
        "link"  => "/images/waters/Badeteich_Hirschstetten.jpeg",
        "name"  => "Badeteich Hirschstetten",
        "desc"  => "Künstlicher Stadtteich; stark frequentiert.",
        "fish"  => [
            "Karpfen" => ["link" => "https://picsum.photos/200"],
            "Barsch"  => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Karpfen","Barsch"],
        "tips" => "Früh/spät fischen; tags viel Badebetrieb.",
    ],
    "Wienerbergteich" => [
        "state" => "Wien",
        "link"  => "/images/waters/Wienerbergteich.jpeg",
        "name"  => "Wienerbergteich",
        "desc"  => "Künstliches Stadtgewässer am Wienerberg.",
        "fish"  => [
            "Karpfen" => ["link" => "https://picsum.photos/200"],
            "Barsch"  => ["link" => "https://picsum.photos/200"],
        ],
        "reg_refs" => ["Karpfen","Barsch"],
        "tips" => "Unauffällige Präsentationen; Randstrukturen abklopfen.",
    ],

];

