<?php

return [
    // 🌊 Kärnten
    "Wörthersee" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Woerthersee.jpg",
        "name" => "Wörthersee",
        "desc" => "Größter See Kärntens mit strukturreichen Buchten, Schilfkanten und tiefem Freiwasser. Sehr artenreich; gute Infrastruktur (Boote, Karten, Stege).",
        "fish" => [
            "Reinanke"       => ["link" => "/images/fish/Renke.jpg"],
            "Hecht"          => ["link" => "/images/fish/Hecht.jpg"],
            "Zander"         => ["link" => "/images/fish/Zander.jpg"],
            "Spiegelkarpfen" => ["link" => "/images/fish/Spiegelkarpfen.jpg"],
            "Wels"           => ["link" => "/images/fish/Wels.jpeg"],
            "Barsch"         => ["link" => "/images/fish/Barsch.jpeg"],
        ],
        "tips" => "Frühjahr: flach an Schilfkanten auf Hecht (Jerkbait, Swimbait). Sommer: Renken mit Hegene über Kanten (12–20 m). Nacht: Zander mit Gummifisch/Jig an Steinpackungen; Boilies & Partikel für Karpfen in ruhigen Buchten.",
    ],
    "Ossiacher See" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Ossiachersee.jpeg",
        "name" => "Ossiacher See",
        "desc" => "Abwechslung pur zwischen Gerlitzen und Tauern: Schilf, Plateaus, Kanten bis ~50 m. Hecht, Zander, Karpfen, Renke, Barsch.",
        "fish" => [
            "Hecht"          => ["link" => "/images/fish/Hecht.jpg"],
            "Zander"         => ["link" => "/images/fish/Zander.jpg"],
            "Spiegelkarpfen" => ["link" => "/images/fish/Spiegelkarpfen.jpg"],
            "Reinanke"       => ["link" => "/images/fish/Renke.jpg"],
            "Wels"           => ["link" => "/images/fish/Wels.jpeg"],
            "Barsch"         => ["link" => "/images/fish/Barsch.jpeg"],
        ],
        "tips" => "Zander ab Juni nachts an Hafenmauern/Drop-offs (3–8 m) mit Low-Action Shads. Hecht im Frühsommer in Krautfeldern mit Spinnerbait. Renke tagsüber mit feiner Hegene über Freiwasser-Schwärmen.",
    ],
    "Millstätter See" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Millstaettersee.jpeg",
        "name" => "Millstätter See",
        "desc" => "Tiefes Klarwassergewässer mit Reinanke und Seeforelle als Highlights; auch starke Hechte.",
        "fish" => [
            "Reinanke"       => ["link" => "/images/fish/Renke.jpg"],
            "Seeforelle"     => ["link" => "/images/fish/Seeforelle.jpeg"],
            "Hecht"          => ["link" => "/images/fish/Hecht.jpg"],
            "Spiegelkarpfen" => ["link" => "/images/fish/Spiegelkarpfen.jpg"],
            "Barsch"         => ["link" => "/images/fish/Barsch.jpeg"],
        ],
        "tips" => "Frühjahr/Spätherbst: Seeforelle mit Schleppködern (Wobbler, Blinkerlöffel) entlang Kanten. Renke: feine 0,12–0,16er, Hegene #16–18; Echolot hilfreich.",
    ],
    "Weißensee" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Weissensee.jpeg",
        "name" => "Weißensee",
        "desc" => "Höchstgelegener großer See Kärntens; sehr klar, kühl, salmonidenstark.",
        "fish" => [
            "Seeforelle"  => ["link" => "/images/fish/Seeforelle.jpeg"],
            "Seesaibling" => ["link" => "/images/fish/Seesaibling.jpeg"],
            "Reinanke"    => ["link" => "/images/fish/Renke.jpg"],
            "Hecht"       => ["link" => "/images/fish/Hecht.jpg"],
        ],
        "tips" => "Früher Morgen: Saiblinge flacher (5–12 m) mit Naturköder (Wurm, Made) an feinen Montagen. Sommer: Seeforelle tiefer schleppen (Downrigger/Paravan).",
    ],
    "Faaker See" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Faakersee.jpeg",
        "name" => "Faaker See",
        "desc" => "Türkis, klar und sonnenreich – Barsche, Hechte und Renken.",
        "fish" => [
            "Renke"          => ["link" => "/images/fish/Renke.jpg"],
            "Hecht"          => ["link" => "/images/fish/Hecht.jpg"],
            "Barsch"         => ["link" => "/images/fish/Barsch.jpeg"],
            "Spiegelkarpfen" => ["link" => "/images/fish/Spiegelkarpfen.jpg"],
        ],
        "tips" => "Barsch: Microjigs/Drop-Shot an Steinrampen. Hecht: flach mit Jerkbait/fransenlosen Streamern an Krautkanten. Renke: Hegene im Mittelwasser über Tiefen.",
    ],
    "Klopeiner See" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Klopeinersee.jpeg",
        "name" => "Klopeiner See",
        "desc" => "Sehr warmes Sommergewässer – Zander, Hecht, Wels plus kräftige Friedfische.",
        "fish" => [
            "Zander"         => ["link" => "/images/fish/Zander.jpg"],
            "Hecht"          => ["link" => "/images/fish/Hecht.jpg"],
            "Wels"           => ["link" => "/images/fish/Wels.jpeg"],
            "Spiegelkarpfen" => ["link" => "/images/fish/Spiegelkarpfen.jpg"],
            "Reinanke"       => ["link" => "/images/fish/Renke.jpg"],
        ],
        "tips" => "Sommernächte: Zander flach an Sandbänken (5–30 g Jigs, dunkle Shads). Wels: Großköder (Gummi 20–25 cm) in warmen Nächten an Kanten. Tags: Karpfen mit Partikel/Boilie.",
    ],
    "Pressegger See" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Presseggersee.jpeg",
        "name" => "Pressegger See",
        "desc" => "Flach, sonnig, viel Schilf – stark bei Friedfisch; Hecht/Barsch als Bonus.",
        "fish" => [
            "Spiegelkarpfen"  => ["link" => "/images/fish/Spiegelkarpfen.jpg"],
            "Hecht"           => ["link" => "/images/fish/Hecht.jpg"],
            "Barsch"          => ["link" => "/images/fish/Barsch.jpeg"],
            "Rotauge"         => ["link" => "/images/fish/Rotauge.jpeg"],
            "Rotfeder"        => ["link" => "/images/fish/Rotfeder.jpeg"],
        ],
        "tips" => "Karpfen: Randbereiche der Schilfinseln anfüttern; Method Feeder/Boilie. Hecht: Spinnerbait/Jerk über Kraut.",
    ],
    "Längsee" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Laengsee.jpeg",
        "name" => "Längsee",
        "desc" => "Ruhiges Naturgewässer mit Kraut- und Schilfzonen.",
        "fish" => [
            "Spiegelkarpfen" => ["link" => "/images/fish/Spiegelkarpfen.jpg"],
            "Schleie"        => ["link" => "/images/fish/schleie.jpg"],
            "Hecht"          => ["link" => "/images/fish/Hecht.jpg"],
            "Wels"           => ["link" => "/images/fish/Wels.jpeg"],
            "Barsch"         => ["link" => "/images/fish/Barsch.jpeg"],
        ],
        "tips" => "Flachwasser im Frühsommer: Schleie auf Wurm/Mais. Hecht entlang Schilfkanten mit langsam geführten Softbaits.",
    ],
    "Brennsee" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Brennsee.jpeg",
        "name" => "Brennsee",
        "desc" => "Auch Feldsee; ruhige Buchten und Krautbänke, gemischter Bestand.",
        "fish" => [
            "Hecht"          => ["link" => "/images/fish/Hecht.jpg"],
            "Spiegelkarpfen" => ["link" => "/images/fish/Spiegelkarpfen.jpg"],
            "Renke"          => ["link" => "/images/fish/Renke.jpg"],
            "Schleie"        => ["link" => "/images/fish/schleie.jpg"],
            "Barsch"         => ["link" => "/images/fish/Barsch.jpeg"],
        ],
        "tips" => "Sommer: Barsch mit kleinen Cranks an Stein-/Holzstrukturen. Abends: Hecht mit Topwater über Krautfeldern.",
    ],
    "Afritzer See" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Afritzersee.jpeg",
        "name" => "Afritzer See",
        "desc" => "Idyllischer Gegendtal-See; kurze Wege, viel Ruhe.",
        "fish" => [
            "Hecht"   => ["link" => "/images/fish/Hecht.jpg"],
            "Spiegelkarpfen" => ["link" => "/images/fish/Spiegelkarpfen.jpg"],
            "Barsch"  => ["link" => "/images/fish/Barsch.jpeg"],
            "Rotauge" => ["link" => "/images/fish/Rotauge.jpeg"],
            "Rotfeder" => ["link" => "/images/fish/Rotfeder.jpeg"],
        ],
        "tips" => "Ufernah morgens: Barsch auf Drop-Shot. Karpfen tagsüber am Futterplatz (Method/Inline-Feeder).",
    ],
    "Urbansee" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Urbansee.jpeg",
        "name" => "Urbansee",
        "desc" => "Kleiner Waldsee; sehr friedfischlastig, punktuell Hecht.",
        "fish" => [
            "Spiegelkarpfen" => ["link" => "/images/fish/Spiegelkarpfen.jpg"],
            "Schleie"        => ["link" => "/images/fish/schleie.jpg"],
            "Hecht"          => ["link" => "/images/fish/Hecht.jpg"],
            "Barsch"         => ["link" => "/images/fish/Barsch.jpeg"],
        ],
        "tips" => "Leise präsentieren: Pole/Match & Brotflocke im Kraut; kleine Spinner #2 für Hecht-Trupps.",
    ],
    "Turnersee" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Turnersee.jpeg",
        "name" => "Turnersee",
        "desc" => "Warmer See im Jauntal; Naturparkumgebung, artenreich.",
        "fish" => [
            "Hecht"  => ["link" => "/images/fish/Hecht.jpg"],
            "Wels"   => ["link" => "/images/fish/Wels.jpeg"],
            "Spiegelkarpfen" => ["link" => "/images/fish/Spiegelkarpfen.jpg"],
            "Schleie" => ["link" => "/images/fish/schleie.jpg"],
            "Barsch" => ["link" => "/images/fish/Barsch.jpeg"],
        ],
        "tips" => "Sommernachtsfischen: Zupfermontage/Boilie auf Karpfen; Wels mit totem Köderfisch an Kanten & Ausläufen.",
    ],
    "Silbersee" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Silbersee.jpeg",
        "name" => "Silbersee",
        "desc" => "Stadtnaher Kurztrip-See bei Villach, viel Weißfisch.",
        "fish" => [
            "Rotauge"        => ["link" => "/images/fish/Rotauge.jpeg"],
            "Hecht"          => ["link" => "/images/fish/Hecht.jpg"],
            "Spiegelkarpfen" => ["link" => "/images/fish/Spiegelkarpfen.jpg"],
            "Barsch"         => ["link" => "/images/fish/Barsch.jpeg"],
            "Wels"           => ["link" => "/images/fish/Wels.jpeg"],
        ],
        "tips" => "Feedern mit süßen Mischungen, kleine Haken #12–16. Hecht im Herbst mit schlanken Jerkbaits entlang Steinpackungen.",
    ],
    "Maltschacher See" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Maltschachersee.jpeg",
        "name" => "Maltschacher See",
        "desc" => "Flach & warm, Camping-Umfeld; starke Friedfischzonen.",
        "fish" => [
            "Spiegelkarpfen" => ["link" => "/images/fish/Spiegelkarpfen.jpg"],
            "Schleie"        => ["link" => "/images/fish/schleie.jpg"],
            "Hecht"          => ["link" => "/images/fish/Hecht.jpg"],
            "Barsch"         => ["link" => "/images/fish/Barsch.jpeg"],
        ],
        "tips" => "Frühjahr: Schleie auf Wurm/Mais in Krautfenstern. Karpfen: flach anfüttern, unauffällige Rigs.",
    ],
    "Keutschacher See" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Keutschachersee.jpeg",
        "name" => "Keutschacher See",
        "desc" => "Natursee im Seental; viel Kraut, Weißfisch, Karpfen, Schleie.",
        "fish" => [
            "Spiegelkarpfen" => ["link" => "/images/fish/Spiegelkarpfen.jpg"],
            "Schleie"        => ["link" => "/images/fish/schleie.jpg"],
            "Hecht"          => ["link" => "/images/fish/Hecht.jpg"],
            "Rotauge"        => ["link" => "/images/fish/Rotauge.jpeg"],
        ],
        "tips" => "Unauffällige Präsentation im Klarwasser; Krautkanten systematisch absuchen (Texas/Weightless).",
    ],
    "Rauschelesee" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Rauschelesee.jpeg",
        "name" => "Rauschelesee",
        "desc" => "Kleiner, warmer See südlich des Wörthersees; Friedfischfokus.",
        "fish" => [
            "Spiegelkarpfen" => ["link" => "/images/fish/Spiegelkarpfen.jpg"],
            "Schleie"        => ["link" => "/images/fish/schleie.jpg"],
            "Barsch"         => ["link" => "/images/fish/Barsch.jpeg"],
        ],
        "tips" => "Leise Fütterung, kleine Köder. Barsch-Trupps mit Spinnern & kleinen Gummis absuchen.",
    ],
    "Gösselsdorfer See" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Goesselsdorfersee.jpeg",
        "name" => "Gösselsdorfer See",
        "desc" => "Sehr warm, flach, breite Schilfgürtel.",
        "fish" => [
            "Rotauge" => ["link" => "/images/fish/Rotauge.jpeg"],
            "Hecht"   => ["link" => "/images/fish/Hecht.jpg"],
            "Karpfen" => ["link" => "/images/fish/Schuppenkarpfen.jpeg"],
            "Schleie" => ["link" => "/images/fish/schleie.jpg"],
        ],
        "tips" => "Hecht mit Spinnerbait über Kraut. Friedfisch mit Waggler weit über Schilfkehlen.",
    ],
    "Kraiger See" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Kraigersee.jpeg",
        "name" => "Kraiger See",
        "desc" => "Kleines, ruhiges Seengebiet; naturbelassen.",
        "fish" => [
            "Karpfen" => ["link" => "/images/fish/Schuppenkarpfen.jpeg"],
            "Schleie" => ["link" => "/images/fish/schleie.jpg"],
            "Rotauge" => ["link" => "/images/fish/Rotauge.jpeg"],
        ],
        "tips" => "Früh/Spät: Oberflächenaktivität beobachten; leichte Posenmontagen, Grundruten an Hotspots.",
    ],
    "Goggausee" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Goggausee.jpeg",
        "name" => "Goggausee",
        "desc" => "Waldsee bei Steuerberg; klar, ruhig.",
        "fish" => [
            "Karpfen" => ["link" => "/images/fish/Schuppenkarpfen.jpeg"],
            "Hecht"   => ["link" => "/images/fish/Hecht.jpg"],
            "Barsch"  => ["link" => "/images/fish/Barsch.jpeg"],
        ],
        "tips" => "Hecht im Frühjahr flach; Barsch an Holz/Steg mit kleinen Jigs.",
    ],
    "Forstsee" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Forstsee.jpeg",
        "name" => "Forstsee",
        "desc" => "Stausee oberhalb des Wörthersees; kühles, klares Wasser.",
        "fish" => [
            "Regenbogenforelle" => ["link" => "/images/fish/Forellenbarsch.jpeg"],
            "Bachforelle"       => ["link" => "/images/fish/Bachforelle.jpg"],
            "Hecht"             => ["link" => "/images/fish/Hecht.jpg"],
            "Forellenbarsch"    => ["link" => "/images/fish/Barsch.jpeg"],
        ],
        "tips" => "Forelle: schlanke Wobbler/Spinner im Ejektionsbereich; Hecht mit Jerk/Jig an Felskanten. (Revier kann abweichende Maße/Zeiten vorgeben!)",
    ],
    "Hörzendorfer See" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Hoerzendorfersee.jpeg",
        "name" => "Hörzendorfer See",
        "desc" => "Zollfeld-See mit Flachwasser und Schilf.",
        "fish" => [
            "Karpfen" => ["link" => "/images/fish/Schuppenkarpfen.jpeg"],
            "Hecht"   => ["link" => "/images/fish/Hecht.jpg"],
            "Schleie" => ["link" => "/images/fish/schleie.jpg"],
        ],
        "tips" => "Karpfen: kurze Distanzen, unauffällige Rigs. Hecht: Krautbahnen mit Softjerks.",
    ],
    "St. Leonharder See" => [
        "state" => "Kärnten",
        "link" => "/images/waters/StLeonhardersee.jpeg",
        "name" => "St. Leonharder See",
        "desc" => "Kleines, ruhiges Gewässer nahe St. Veit.",
        "fish" => [
            "Karpfen" => ["link" => "/images/fish/Schuppenkarpfen.jpeg"],
            "Schleie" => ["link" => "/images/fish/schleie.jpg"],
            "Barsch"  => ["link" => "/images/fish/Barsch.jpeg"],
        ],
        "tips" => "Frühmorgens: Posenfischen in Buchten; tagsüber: feine Grundmontagen.",
    ],
    "Hafnersee" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Hafnersee.jpeg",
        "name" => "Hafnersee",
        "desc" => "Natursee im Keutschacher Seental; sensible Schutzzonen.",
        "fish" => [
            "Schuppenkarpfen" => ["link" => "/images/fish/Schuppenkarpfen.jpeg"],
            "Schleie" => ["link" => "/images/fish/schleie.jpg"],
            "Rotfeder" => ["link" => "/images/fish/Rotfeder.jpeg"],
            "Hecht"   => ["link" => "/images/fish/Hecht.jpg"],
        ],
        "tips" => "Krautlücken exakt anwerfen; Waathose meiden (Schutzzonen beachten).",
    ],
    "Vassacher See" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Vassachersee.jpeg",
        "name" => "Vassacher See",
        "desc" => "Stadtnah in Villach; warm & krautig.",
        "fish" => [
            "Rotauge" => ["link" => "/images/fish/Rotauge.jpeg"],
            "Schuppenkarpfen" => ["link" => "/images/fish/Schuppenkarpfen.jpeg"],
            "Hecht"   => ["link" => "/images/fish/Hecht.jpg"],
            "Barsch"  => ["link" => "/images/fish/Barsch.jpeg"],
        ],
        "tips" => "Sommer: Oberflächenbisse auf Barsch (Topwater). Karpfen im Schatten der Schilfkanten.",
    ],
    "Sonnegger See" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Sonneggersee.jpeg",
        "name" => "Sonnegger See",
        "desc" => "Ruhiger See im Jauntal; weißfisch- & karpfenstark.",
        "fish" => [
            "Schuppenkarpfen" => ["link" => "/images/fish/Schuppenkarpfen.jpeg"],
            "Schleie" => ["link" => "/images/fish/schleie.jpg"],
            "Hecht"   => ["link" => "/images/fish/Hecht.jpg"],
        ],
        "tips" => "Bodennahe, unauffällige Präsentation; kleine Köfis am Abend für Hecht.",
    ],
    "Magdalensee" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Magdalensee.jpeg",
        "name" => "Magdalensee",
        "desc" => "Kleiner See nahe Faaker See; warm & krautig.",
        "fish" => [
            "Rotfeder" => ["link" => "/images/fish/Rotfeder.jpeg"],
            "Rotauge" => ["link" => "/images/fish/Rotauge.jpeg"],
            "Hecht"   => ["link" => "/images/fish/Hecht.jpg"],
            "Barsch"  => ["link" => "/images/fish/Barsch.jpeg"],
        ],
        "tips" => "Sommer: Waggler zwischen Krautbahnen; Hecht mit Weedless-Rigs.",
    ],
    "Flatschacher See" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Flatschachersee.jpeg",
        "name" => "Flatschacher See",
        "desc" => "Familienfreundlicher Badesee mit vielen Weißfischen.",
        "fish" => [
            "Schuppenkarpfen" => ["link" => "/images/fish/Schuppenkarpfen.jpeg"],
            "Rotauge" => ["link" => "/images/fish/Rotauge.jpeg"],
            "Schleie" => ["link" => "/images/fish/schleie.jpg"],
            "Hecht"   => ["link" => "/images/fish/Hecht.jpg"],
        ],
        "tips" => "Feeder & Method dicht am Schilfsaum; Hecht mit Spinner #4 an Kanten.",
    ],
    "St. Andräer See" => [
        "state" => "Kärnten",
        "link" => "/images/waters/StAndraeersee.jpeg",
        "name" => "St. Andräer See",
        "desc" => "Badesee im Lavanttal; unkompliziert zugänglich.",
        "fish" => [
            "Schuppenkarpfen" => ["link" => "/images/fish/Schuppenkarpfen.jpeg"],
            "Schleie" => ["link" => "/images/fish/schleie.jpg"],
            "Barsch"  => ["link" => "/images/fish/Barsch.jpeg"],
            "Hecht"   => ["link" => "/images/fish/Hecht.jpg"],
        ],
        "tips" => "Karpfen mit Partikelmischung vorbadender Bereiche; Barsch an Steganlagen.",
    ],
    "Drau (Ktn Abschnitt)" => [
        "state" => "Kärnten",
        "link" => "/images/waters/Millstättersee.jpeg",
        "name" => "Drau",
        "desc" => "Großer Fluss mit stromtypischen Abschnitten.",
        "fish" => [
            "Äsche"  => ["link" => "/images/fish/Äsche.jpeg"],
            "Huchen" => ["link" => "/images/fish/Huchen.jpg"],
            "Barbe"  => ["link" => "/images/fish/Barbe.jpeg"],
        ],
    ],

    // 🌊 Burgenland
    "Neusiedler See" => [
        "state" => "Burgenland",
        "link"  => "/images/waters/Neusiedler_See.jpeg",
        "name"  => "Neusiedler See",
        "desc"  => "Größter Steppensee Mitteleuropas (≈315 km²), UNESCO-Biosphärenpark, flach & schilfreich, geteilt mit Ungarn.",
        "fish"  => [
            "Reinanke" => ["link" => "/images/fish/Renke.jpg"],
            "Hecht"    => ["link" => "/images/fish/Hecht.jpg"],
            "Zander"   => ["link" => "/images/fish/Zander.jpg"],
            "Schuppenkarpfen"  => ["link" => "/images/fish/Schuppenkarpfen.jpeg"],
            "Wels"     => ["link" => "/images/fish/Wels.jpeg"],
            "Barsch"   => ["link" => "/images/fish/Barsch.jpeg"],
            "Schleie"  => ["link" => "/images/fish/schleie.jpg"],
        ],
        "tips" => "Frühjahr: Hecht in Schilfbuchten (Spinnerbait/Swimbait). Sommer: Zander nachts an Kanten (Gummifisch). Karpfen im Schilf auf Partikel.",
    ],
    "Zicksee" => [
        "state" => "Burgenland",
        "link"  => "/images/waters/Zicksee.jpeg",
        "name"  => "Zicksee",
        "desc"  => "Flacher, periodischer Steppensee; Wasserstand schwankt stark, teils trockenfallend.",
        "fish"  => [
            "Hecht"    => ["link" => "/images/fish/Hecht.jpg"],
            "Schuppenkarpfen"  => ["link" => "/images/fish/Schuppenkarpfen.jpeg"],
            "Barsch"   => ["link" => "/images/fish/Barsch.jpeg"],
            "Schleie"  => ["link" => "/images/fish/schleie.jpg"],
        ],
        "tips" => "Frühjahr flach an Schilfkanten; unauffällige Präsentationen wegen Klarwasser/Flachwasser.",
    ],
    "Neufelder See" => [
        "state" => "Burgenland",
        "link"  => "/images/waters/Neufelder_See.jpeg",
        "name"  => "Neufelder See",
        "desc"  => "Klarer Baggersee; Bade- und Tauchrevier.",
        "fish"  => [
            "Hecht"    => ["link" => "/images/fish/Hecht.jpg"],
            "Zander"   => ["link" => "/images/fish/Zander.jpg"],
            "Schuppenkarpfen"  => ["link" => "/images/fish/Schuppenkarpfen.jpeg"],
            "Barsch"   => ["link" => "/images/fish/Barsch.jpeg"],
            "Wels"     => ["link" => "/images/fish/Wels.jpeg"],
        ],
        "tips" => "Zander nachts an Stegen/Strukturen; tags Hecht an Kanten & Krautbetten.",
    ],

    // 🌊 Niederösterreich
    "Lunzer See" => [
        "state" => "Niederösterreich",
        "link"  => "/images/waters/Lunzer_See.jpeg",
        "name"  => "Lunzer See",
        "desc"  => "Einziger natürlicher See Niederösterreichs; klares Bergwasser in den Ybbstaler Alpen.",
        "fish"  => [
            "Reinanke"   => ["link" => "/images/fish/Renke.jpg"],
            "Seeforelle" => ["link" => "/images/fish/Seeforelle.jpeg"],
            "Hecht"      => ["link" => "/images/fish/Hecht.jpg"],
            "Barsch"     => ["link" => "/images/fish/Barsch.jpeg"],
        ],
        "tips" => "Sommer: Renken mit Hegene 10–20 m. Frühjahr/Herbst: Hecht flacher an Schilf & Einläufen.",
    ],
    "Erlaufsee" => [
        "state" => "Niederösterreich",
        "link"  => "/images/waters/Erlaufsee.jpeg",
        "name"  => "Erlaufsee",
        "desc"  => "Klarer Grenzsee zu Steiermark; gute Sichtweiten, Bade- & Tauchsee.",
        "fish"  => [
            "Reinanke"    => ["link" => "/images/fish/Renke.jpg"],
            "Seesaibling" => ["link" => "/images/fish/Bachsaibling.jpeg"],
            "Seeforelle"  => ["link" => "/images/fish/Seeforelle.jpeg"],
            "Hecht"       => ["link" => "/images/fish/Hecht.jpg"],
            "Barsch"      => ["link" => "/images/fish/Barsch.jpeg"],
        ],
        "tips" => "Frühe Saison: Forellen an Kanten/Einläufen. Sommer: Renken tiefer (15–25 m).",
    ],
    "Ottensteiner Stausee" => [
        "state" => "Niederösterreich",
        "link"  => "/images/waters/Ottensteiner_Stausee.jpeg",
        "name"  => "Ottensteiner Stausee",
        "desc"  => "Fjordartige Granitlandschaft am Kamp; viele Buchten, Inseln, Klippen.",
        "fish"  => [
            "Hecht"  => ["link" => "/images/fish/Hecht.jpg"],
            "Zander" => ["link" => "/images/fish/Zander.jpg"],
            "Barsch" => ["link" => "/images/fish/Barsch.jpeg"],
            "Wels"   => ["link" => "/images/fish/Wels.jpeg"],
        ],
        "tips" => "Hecht an Felsabbrüchen (Jerkbait/Swimbait). Zander nachts an Steinpackungen mit Gummifisch.",
    ],
    "Dobra-Stausee" => [
        "state" => "Niederösterreich",
        "link"  => "/images/waters/Dobra_Stausee.jpeg",
        "name"  => "Dobra-Stausee",
        "desc"  => "Ruhige Stausee-Abschnitte, Paddel- und Kletter-Hotspot.",
        "fish"  => [
            "Hecht"   => ["link" => "/images/fish/Hecht.jpg"],
            "Zander"  => ["link" => "/images/fish/Zander.jpg"],
            "Barsch"  => ["link" => "/images/fish/Barsch.jpeg"],
            "Schuppenkarpfen" => ["link" => "/images/fish/Schuppenkarpfen.jpeg"],
        ],
        "tips" => "Sommerabends: Zander an Kanten. Hecht tagsüber an Holz & Fels.",
    ],
    "Thurnberger Stausee" => [
        "state" => "Niederösterreich",
        "link"  => "/images/waters/Thurnberger_Stausee.jpeg",
        "name"  => "Thurnberger Stausee",
        "desc"  => "Kamp-Stausee mit ausgedehnten Uferzonen und Kanten.",
        "fish"  => [
            "Hecht"  => ["link" => "/images/fish/Hecht.jpg"],
            "Zander" => ["link" => "/images/fish/Zander.jpg"],
            "Barsch" => ["link" => "/images/fish/Barsch.jpeg"],
            "Wels"   => ["link" => "/images/fish/Wels.jpeg"],
        ],
        "tips" => "Zander bei Dämmerung; Barsch truppweise an Steinpackungen (Jig/Minnow).",
    ],
    "Wienerwaldsee" => [
        "state" => "Niederösterreich",
        "link"  => "/images/waters/Wienerwaldsee.jpeg",
        "name"  => "Wienerwaldsee",
        "desc"  => "Speichersee mit Geschichte der Wiener Wasserversorgung; Ufer teils bewaldet.",
        "fish"  => [
            "Hecht"   => ["link" => "/images/fish/Hecht.jpg"],
            "Schuppenkarpfen" => ["link" => "/images/fish/Schuppenkarpfen.jpeg"],
            "Barsch"  => ["link" => "/images/fish/Barsch.jpeg"],
        ],
        "tips" => "Frühjahr flach; Sommer nachts Karpfen mit Boilies in ruhigen Zonen.",
    ],

    // 🌊 Oberösterreich
    "Attersee" => [
        "state" => "Oberösterreich",
        "link"  => "/images/waters/Attersee.jpeg",
        "name"  => "Attersee",
        "desc"  => "Größter Binnen-See AT (≈46 km²), sehr klar, tiefe Kanten; Segeln & Tauchen.",
        "fish"  => [
            "Reinanke"    => ["link" => "/images/fish/Renke.jpg"],
            "Seesaibling" => ["link" => "/images/fish/Bachsaibling.jpeg"],
            "Hecht"       => ["link" => "/images/fish/Hecht.jpg"],
            "Zander"      => ["link" => "/images/fish/Zander.jpg"],
            "Barsch"      => ["link" => "/images/fish/Barsch.jpeg"],
            "Schuppenkarpfen"     => ["link" => "/images/fish/Schuppenkarpfen.jpeg"],
        ],
        "tips" => "Renken im Sommer 15–25 m (Hegene). Hecht im Frühjahr flach; Zander nachts an Steinpackungen.",
    ],
    "Traunsee" => [
        "state" => "Oberösterreich",
        "link"  => "/images/waters/Traunsee.jpeg",
        "name"  => "Traunsee",
        "desc"  => "Sehr tief (bis ~191 m), fjordartige Ufer, klares Wasser.",
        "fish"  => [
            "Reinanke"    => ["link" => "/images/fish/Renke.jpg"],
            "Seesaibling" => ["link" => "/images/fish/Bachsaibling.jpeg"],
            "Seeforelle"  => ["link" => "/images/fish/Seeforelle.jpeg"],
            "Hecht"       => ["link" => "/images/fish/Hecht.jpg"],
            "Barsch"      => ["link" => "/images/fish/Barsch.jpeg"],
        ],
        "tips" => "Forellen/ Saibling tief über Kanten schleppen; Renken vertikal.",
    ],
    "Mondsee" => [
        "state" => "Oberösterreich",
        "link"  => "/images/waters/Mondsee.jpeg",
        "name"  => "Mondsee",
        "desc"  => "Karstsee, klare Sicht, markante Uferkanten.",
        "fish"  => [
            "Reinanke" => ["link" => "/images/fish/Renke.jpg"],
            "Hecht"    => ["link" => "/images/fish/Hecht.jpg"],
            "Zander"   => ["link" => "/images/fish/Zander.jpg"],
            "Barsch"   => ["link" => "/images/fish/Barsch.jpeg"],
        ],
        "tips" => "Hecht im Frühjahr flach; Renken im Sommer tiefer mit Hegene.",
    ],
    "Wolfgangsee (OO Anteil)" => [
        "state" => "Oberösterreich",
        "link"  => "/images/waters/Wolfgangsee_OO_Anteil.jpeg",
        "name"  => "Wolfgangsee",
        "desc"  => "Grenzsee zu Salzburg; klare Buchten und Steilufer.",
        "fish"  => [
            "Reinanke" => ["link" => "/images/fish/Renke.jpg"],
            "Hecht"    => ["link" => "/images/fish/Hecht.jpg"],
            "Barsch"   => ["link" => "/images/fish/Barsch.jpeg"],
        ],
        "tips" => "Renken über Kanten; Hecht in Kraut- und Schilfzonen.",
    ],
    "Hallstätter See" => [
        "state" => "Oberösterreich",
        "link"  => "/images/waters/Hallstaetter_See.jpeg",
        "name"  => "Hallstätter See",
        "desc"  => "UNESCO-Kulisse, kaltes, klares Wasser; tiefe Ufer.",
        "fish"  => [
            "Reinanke"    => ["link" => "/images/fish/Renke.jpg"],
            "Seesaibling" => ["link" => "/images/fish/Bachsaibling.jpeg"],
            "Seeforelle"  => ["link" => "/images/fish/Seeforelle.jpeg"],
        ],
        "tips" => "Schleppen auf Forelle/ Saibling entlang tiefer Kanten; Renken vertikal.",
    ],
    "Irrsee" => [
        "state" => "Oberösterreich",
        "link"  => "/images/waters/Irrsee.jpeg",
        "name"  => "Irrsee (Zeller See)",
        "desc"  => "Relativ warm; Flachwasserzonen mit Krautgürteln.",
        "fish"  => [
            "Hecht"   => ["link" => "/images/fish/Hecht.jpg"],
            "Schuppenkarpfen" => ["link" => "/images/fish/Schuppenkarpfen.jpeg"],
            "Barsch"  => ["link" => "/images/fish/Barsch.jpeg"],
        ],
        "tips" => "Hecht flach im Frühjahr; Karpfen in Buchten (Boilies/Partikel).",
    ],
    "Almsee" => [
        "state" => "Oberösterreich",
        "link"  => "/images/waters/Almsee.jpeg",
        "name"  => "Almsee",
        "desc"  => "Türkisgrüner Bergsee im Naturschutzgebiet; sehr klar.",
        "fish"  => [
            "Seeforelle" => ["link" => "/images/fish/Seeforelle.jpeg"],
            "Barsch"     => ["link" => "/images/fish/Barsch.jpeg"],
        ],
        "tips" => "Klares Wasser: feine Vorfächer und natürliche Köderfarben.",
    ],
    "Vorderer Gosausee" => [
        "state" => "Oberösterreich",
        "link"  => "/images/waters/Vorderer_Gosausee.jpeg",
        "name"  => "Vorderer Gosausee",
        "desc"  => "Sehr klarer Bergsee; Dachsteinblick.",
        "fish"  => [
            "Seeforelle" => ["link" => "/images/fish/Seeforelle.jpeg"],
            "Saibling"   => ["link" => "/images/fish/Bachsaibling.jpeg"],
        ],
        "tips" => "Leichte Rigs, unauffällige Präsentation, frühe/ späte Tageszeiten.",
    ],
    "Hinterer Gosausee" => [
        "state" => "Oberösterreich",
        "link"  => "/images/waters/Hinterer_Gosausee.jpeg",
        "name"  => "Hinterer Gosausee",
        "desc"  => "Abgelegener Bergsee; glasklar.",
        "fish"  => [
            "Seeforelle" => ["link" => "/images/fish/Seeforelle.jpeg"],
            "Saibling"   => ["link" => "/images/fish/Bachsaibling.jpeg"],
        ],
        "tips" => "Still & klar – weite Würfe, feines Gerät.",
    ],
    "Vorderer Langbathsee" => [
        "state" => "Oberösterreich",
        "link"  => "/images/waters/Vorderer_Langbathsee.jpeg",
        "name"  => "Vorderer Langbathsee",
        "desc"  => "Klarer Bergsee nahe Ebensee.",
        "fish"  => [
            "Seeforelle" => ["link" => "/images/fish/Seeforelle.jpeg"],
            "Saibling"   => ["link" => "/images/fish/Bachsaibling.jpeg"],
        ],
        "tips" => "Früh & spät aktiv; Schlauchboote/ Belly (falls erlaubt) vorteilhaft.",
    ],
    "Hinterer Langbathsee" => [
        "state" => "Oberösterreich",
        "link"  => "/images/waters/Hinterer_Langbathsee.jpeg",
        "name"  => "Hinterer Langbathsee",
        "desc"  => "Kleiner, klarer Bergsee im Waldkessel.",
        "fish"  => [
            "Seeforelle" => ["link" => "/images/fish/Seeforelle.jpeg"],
            "Saibling"   => ["link" => "/images/fish/Bachsaibling.jpeg"],
        ],
        "tips" => "Unauffällige Montagen; Uferpirsch.",
    ],
    // Ergänzt OÖ (Auswahl)
    "Pleschinger See" => [
        "state" => "Oberösterreich",
        "link"  => "/images/waters/Pleschinger_See.jpeg",
        "name"  => "Pleschinger See",
        "desc"  => "Bade-/Angelsee bei Linz; krautreiche Ufer.",
        "fish"  => [
            "Hecht"   => ["link" => "/images/fish/Hecht.jpg"],
            "Schuppenkarpfen" => ["link" => "/images/fish/Schuppenkarpfen.jpeg"],
            "Barsch"  => ["link" => "/images/fish/Barsch.jpeg"],
        ],
        "tips" => "Früh/Spät fischen; tagsüber viel Badebetrieb.",
    ],

    // 🌊 Salzburg
    "Zeller See" => [
        "state" => "Salzburg",
        "link"  => "/images/waters/Zeller_See.jpeg",
        "name"  => "Zeller See",
        "desc"  => "Alpiner, klarer Badesee mit Gletscherblick.",
        "fish"  => [
            "Reinanke"   => ["link" => "/images/fish/Renke.jpg"],
            "Seeforelle" => ["link" => "/images/fish/Seeforelle.jpeg"],
            "Hecht"      => ["link" => "/images/fish/Hecht.jpg"],
            "Schuppenkarpfen"    => ["link" => "/images/fish/Schuppenkarpfen.jpeg"],
            "Barsch"     => ["link" => "/images/fish/Barsch.jpeg"],
        ],
        "tips" => "Frühjahr: Forelle an Kanten/Einläufen. Sommer: Renken 10–20 m (Hegene).",
    ],
    "Wallersee" => [
        "state" => "Salzburg",
        "link"  => "/images/waters/Wallersee.jpeg",
        "name"  => "Wallersee",
        "desc"  => "Relativ flach, windoffen; ausgedehnte Schilfzonen.",
        "fish"  => [
            "Hecht"   => ["link" => "/images/fish/Hecht.jpg"],
            "Zander"  => ["link" => "/images/fish/Zander.jpg"],
            "Karpfen" => ["link" => "/images/fish/Schuppenkarpfen.jpeg"],
            "Barsch"  => ["link" => "/images/fish/Barsch.jpeg"],
            "Wels"    => ["link" => "/images/fish/Wels.jpeg"],
        ],
        "tips" => "Hecht im Frühjahr in Schilfbuchten; Zander nachts an Kanten.",
    ],
    "Mattsee" => [
        "state" => "Salzburg",
        "link"  => "/images/waters/Mattsee.jpeg",
        "name"  => "Mattsee",
        "desc"  => "Teil der Trumer Seen; strukturreiche Ufer mit Schilf & Buchten.",
        "fish"  => [
            "Hecht"   => ["link" => "/images/fish/Hecht.jpg"],
            "Zander"  => ["link" => "/images/fish/Zander.jpg"],
            "Barsch"  => ["link" => "/images/fish/Barsch.jpeg"],
            "Schuppenkarpfen" => ["link" => "/images/fish/Schuppenkarpfen.jpeg"],
        ],
        "tips" => "Frühsommer: Hecht im Kraut; Barsch an Steinpackungen (Jig/Crank).",
    ],
    "Obertrumer See" => [
        "state" => "Salzburg",
        "link"  => "/images/waters/Obertrumer_See.jpeg",
        "name"  => "Obertrumer See",
        "desc"  => "Größter der Trumer Seen; weiträumige Flachwasserbereiche.",
        "fish"  => [
            "Hecht"   => ["link" => "/images/fish/Hecht.jpg"],
            "Zander"  => ["link" => "/images/fish/Zander.jpg"],
            "Barsch"  => ["link" => "/images/fish/Barsch.jpeg"],
            "Schuppenkarpfen" => ["link" => "/images/fish/Schuppenkarpfen.jpeg"],
        ],
        "tips" => "Abend-/Nacht: Zander an Übergängen von Flach- zu Tiefwasser.",
    ],
    "Grabensee" => [
        "state" => "Salzburg",
        "link"  => "/images/waters/Grabensee.jpeg",
        "name"  => "Grabensee",
        "desc"  => "Kleiner, naturnaher Teil der Trumer Seen; Schilfgürtel.",
        "fish"  => [
            "Hecht"   => ["link" => "/images/fish/Hecht.jpg"],
            "Barsch"  => ["link" => "/images/fish/Barsch.jpeg"],
            "Schuppenkarpfen" => ["link" => "/images/fish/Schuppenkarpfen.jpeg"],
        ],
        "tips" => "Hecht in Buchten; Barsch an Schilfkanten mit leichten Jigs.",
    ],
    "Fuschlsee" => [
        "state" => "Salzburg",
        "link"  => "/images/waters/Fuschlsee.jpeg",
        "name"  => "Fuschlsee",
        "desc"  => "Sehr klares Wasser, Uferwanderweg; steile Kanten.",
        "fish"  => [
            "Reinanke"   => ["link" => "/images/fish/Renke.jpg"],
            "Seeforelle" => ["link" => "/images/fish/Seeforelle.jpeg"],
            "Hecht"      => ["link" => "/images/fish/Hecht.jpg"],
            "Barsch"     => ["link" => "/images/fish/Barsch.jpeg"],
        ],
        "tips" => "Tagesrandzeiten & feine Vorfächer; Renken tiefer im Sommer.",
    ],
    "Hintersee Faistenau" => [
        "state" => "Salzburg",
        "link"  => "/images/waters/Hintersee_Faistenau.jpeg",
        "name"  => "Hintersee (Faistenau)",
        "desc"  => "Kleiner, klarer Bergsee; familienfreundlich.",
        "fish"  => [
            "Seeforelle" => ["link" => "/images/fish/Seeforelle.jpeg"],
            "Barsch"     => ["link" => "/images/fish/Barsch.jpeg"],
        ],
        "tips" => "Leichte Rigs; kleine Minnows/Spinner.",
    ],
    "Wolfgangsee (Sbg Anteil)" => [
        "state" => "Salzburg",
        "link"  => "/images/waters/Wolfgangsee_Sbg_Anteil.jpeg",
        "name"  => "Wolfgangsee",
        "desc"  => "Grenzsee zu Oberösterreich; klare Buchten, touristische Infrastruktur.",
        "fish"  => [
            "Reinanke" => ["link" => "/images/fish/Renke.jpg"],
            "Hecht"    => ["link" => "/images/fish/Hecht.jpg"],
            "Barsch"   => ["link" => "/images/fish/Barsch.jpeg"],
        ],
        "tips" => "Renken über Kanten, Hecht im Krautgürtel.",
    ],

    // 🌊 Steiermark
    "Grundlsee" => [
        "state" => "Steiermark",
        "link"  => "/images/waters/Grundlsee.jpeg",
        "name"  => "Grundlsee",
        "desc"  => "‚Steirisches Meer‘; großer Klarwassersee im Ausseerland.",
        "fish"  => [
            "Reinanke"    => ["link" => "/images/fish/Renke.jpg"],
            "Seesaibling" => ["link" => "/images/fish/Bachsaibling.jpeg"],
            "Hecht"       => ["link" => "/images/fish/Hecht.jpg"],
            "Barsch"      => ["link" => "/images/fish/Barsch.jpeg"],
        ],
        "tips" => "Sommer: Renken tiefer (Hegene). Hecht an Kraut- & Schilfkanten.",
    ],
    "Altausseer See" => [
        "state" => "Steiermark",
        "link"  => "/images/waters/Altausseer_See.jpeg",
        "name"  => "Altausseer See",
        "desc"  => "Smaragdgrüner, klarer See am Loser; steile Ufer.",
        "fish"  => [
            "Reinanke"    => ["link" => "/images/fish/Renke.jpg"],
            "Seesaibling" => ["link" => "/images/fish/Bachsaibling.jpeg"],
            "Seeforelle"  => ["link" => "/images/fish/Seeforelle.jpeg"],
        ],
        "tips" => "Feine Hegenen/Fliegen; Schleppangeln tief an Kanten.",
    ],
    "Toplitzsee" => [
        "state" => "Steiermark",
        "link"  => "/images/waters/Toplitzsee.jpeg",
        "name"  => "Toplitzsee",
        "desc"  => "Mystisch, meromiktisch; beschränkter Zugang/Schutzauflagen.",
        "fish"  => [
            "Saibling"   => ["link" => "/images/fish/Bachsaibling.jpeg"],
            "Seeforelle" => ["link" => "/images/fish/Seeforelle.jpeg"],
        ],
        "tips" => "Vorab lokale Bestimmungen genau prüfen.",
    ],
    "Erlaufsee (Stmk Anteil)" => [
        "state" => "Steiermark",
        "link"  => "/images/waters/Erlaufsee_Stmk_Anteil.jpeg",
        "name"  => "Erlaufsee (Stmk-Anteil)",
        "desc"  => "Klarer Grenzsee zu Niederösterreich.",
        "fish"  => [
            "Reinanke"    => ["link" => "/images/fish/Renke.jpg"],
            "Seesaibling" => ["link" => "/images/fish/Bachsaibling.jpeg"],
            "Seeforelle"  => ["link" => "/images/fish/Seeforelle.jpeg"],
            "Hecht"       => ["link" => "/images/fish/Hecht.jpg"],
            "Barsch"      => ["link" => "/images/fish/Barsch.jpeg"],
        ],
        "tips" => "Ähnlich NÖ-Seite: Renken tiefer, Forellen an Kanten.",
    ],
    "Leopoldsteiner See" => [
        "state" => "Steiermark",
        "link"  => "/images/waters/Leopoldsteiner_See.jpeg",
        "name"

    ]
];
